// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/storage-object.service.proto

/* eslint-disable */
import { type Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import {
  type GrpcProxyControllerFactory,
  type GrpcProxyControllerFactoryParams,
  type GrpcProxyControllerFactoryResult,
  type GrpcProxyMethodParams,
} from '../__compiler__';
import { GrpcBooleanResult, type GrpcGetListRequest, type GrpcIdField } from '../common/service';
import {
  type GrpcStorageObjectCreate,
  type GrpcStorageObjectExistsFolderRequest,
  type GrpcStorageObjectGetFoldersRequest,
  GrpcStorageObjectGetFoldersResponse,
  GrpcStorageObjectGetListResponse,
  GrpcStorageObjectList,
  GrpcStorageObjectPopulated,
  type GrpcStorageObjectRequest,
  type GrpcStorageObjectUpdateByIdRequest,
} from './messages/storage-object.messages';
import { GrpcStorageObject } from './models/storage-object';

export interface GrpcStorageObjectServiceClient {
  getById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcStorageObjectPopulated>;

  getMany(
    request: GrpcStorageObjectRequest,
    metadata?: Metadata,
  ): Observable<GrpcStorageObjectList>;

  getList(
    request: GrpcGetListRequest,
    metadata?: Metadata,
  ): Observable<GrpcStorageObjectGetListResponse>;

  getFolders(
    request: GrpcStorageObjectGetFoldersRequest,
    metadata?: Metadata,
  ): Observable<GrpcStorageObjectGetFoldersResponse>;

  isExistsFolder(
    request: GrpcStorageObjectExistsFolderRequest,
    metadata?: Metadata,
  ): Observable<GrpcBooleanResult>;

  createOne(request: GrpcStorageObjectCreate, metadata?: Metadata): Observable<GrpcStorageObject>;

  updateById(
    request: GrpcStorageObjectUpdateByIdRequest,
    metadata?: Metadata,
  ): Observable<GrpcStorageObject>;

  deleteById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcStorageObject>;
}

export interface GrpcStorageObjectServiceController {
  getById(
    request: GrpcIdField,
    metadata?: Metadata,
  ):
    | Promise<GrpcStorageObjectPopulated>
    | Observable<GrpcStorageObjectPopulated>
    | GrpcStorageObjectPopulated;

  getMany(
    request: GrpcStorageObjectRequest,
    metadata?: Metadata,
  ): Promise<GrpcStorageObjectList> | Observable<GrpcStorageObjectList> | GrpcStorageObjectList;

  getList(
    request: GrpcGetListRequest,
    metadata?: Metadata,
  ):
    | Promise<GrpcStorageObjectGetListResponse>
    | Observable<GrpcStorageObjectGetListResponse>
    | GrpcStorageObjectGetListResponse;

  getFolders(
    request: GrpcStorageObjectGetFoldersRequest,
    metadata?: Metadata,
  ):
    | Promise<GrpcStorageObjectGetFoldersResponse>
    | Observable<GrpcStorageObjectGetFoldersResponse>
    | GrpcStorageObjectGetFoldersResponse;

  isExistsFolder(
    request: GrpcStorageObjectExistsFolderRequest,
    metadata?: Metadata,
  ): Promise<GrpcBooleanResult> | Observable<GrpcBooleanResult> | GrpcBooleanResult;

  createOne(
    request: GrpcStorageObjectCreate,
    metadata?: Metadata,
  ): Promise<GrpcStorageObject> | Observable<GrpcStorageObject> | GrpcStorageObject;

  updateById(
    request: GrpcStorageObjectUpdateByIdRequest,
    metadata?: Metadata,
  ): Promise<GrpcStorageObject> | Observable<GrpcStorageObject> | GrpcStorageObject;

  deleteById(
    request: GrpcIdField,
    metadata?: Metadata,
  ): Promise<GrpcStorageObject> | Observable<GrpcStorageObject> | GrpcStorageObject;
}

function StorageObjectServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getById',
      'getMany',
      'getList',
      'getFolders',
      'isExistsFolder',
      'createOne',
      'updateById',
      'deleteById',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('StorageObjectService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('StorageObjectService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

const STORAGE_OBJECT_SERVICE_NAME = 'StorageObjectService';

interface GrpcStorageObjectProxyMethodParams {
  getById?: GrpcProxyMethodParams<GrpcIdField>;
  getMany?: GrpcProxyMethodParams<GrpcStorageObjectRequest>;
  getList?: GrpcProxyMethodParams<GrpcGetListRequest>;
  getFolders?: GrpcProxyMethodParams<GrpcStorageObjectGetFoldersRequest>;
  isExistsFolder?: GrpcProxyMethodParams<GrpcStorageObjectExistsFolderRequest>;
  createOne?: GrpcProxyMethodParams<GrpcStorageObjectCreate>;
  updateById?: GrpcProxyMethodParams<GrpcStorageObjectUpdateByIdRequest>;
  deleteById?: GrpcProxyMethodParams<GrpcIdField>;
}

export const GrpcStorageObjectService = {
  name: 'StorageObjectService',
  definition: {
    package: 'storage',
    protoPath: 'storage/storage-object.service.proto',
  },
  proxyFactory: (
    methodParams: GrpcStorageObjectProxyMethodParams = {},
  ): GrpcProxyControllerFactory => {
    return (
      controllerParams: GrpcProxyControllerFactoryParams,
    ): GrpcProxyControllerFactoryResult => {
      const { GrpcController, GrpcMethod, InjectGrpcService, proxyPipes } = controllerParams;

      @GrpcController()
      @StorageObjectServiceControllerMethods()
      class GrpcStorageObjectProxyController {
        constructor(
          @InjectGrpcService(STORAGE_OBJECT_SERVICE_NAME)
          private readonly client: GrpcStorageObjectServiceClient,
        ) {}

        @GrpcMethod(methodParams.getById)
        getById(
          request: GrpcIdField,
          metadata?: Metadata,
        ):
          | GrpcStorageObjectPopulated
          | Promise<GrpcStorageObjectPopulated>
          | Observable<GrpcStorageObjectPopulated> {
          //@ts-ignore
          return this.client.getById(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getMany)
        getMany(
          request: GrpcStorageObjectRequest,
          metadata?: Metadata,
        ):
          | GrpcStorageObjectList
          | Promise<GrpcStorageObjectList>
          | Observable<GrpcStorageObjectList> {
          //@ts-ignore
          return this.client.getMany(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getList)
        getList(
          request: GrpcGetListRequest,
          metadata?: Metadata,
        ):
          | GrpcStorageObjectGetListResponse
          | Promise<GrpcStorageObjectGetListResponse>
          | Observable<GrpcStorageObjectGetListResponse> {
          //@ts-ignore
          return this.client.getList(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getFolders)
        getFolders(
          request: GrpcStorageObjectGetFoldersRequest,
          metadata?: Metadata,
        ):
          | GrpcStorageObjectGetFoldersResponse
          | Promise<GrpcStorageObjectGetFoldersResponse>
          | Observable<GrpcStorageObjectGetFoldersResponse> {
          //@ts-ignore
          return this.client.getFolders(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.isExistsFolder)
        isExistsFolder(
          request: GrpcStorageObjectExistsFolderRequest,
          metadata?: Metadata,
        ): GrpcBooleanResult | Promise<GrpcBooleanResult> | Observable<GrpcBooleanResult> {
          //@ts-ignore
          return this.client.isExistsFolder(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.createOne)
        createOne(
          request: GrpcStorageObjectCreate,
          metadata?: Metadata,
        ): GrpcStorageObject | Promise<GrpcStorageObject> | Observable<GrpcStorageObject> {
          //@ts-ignore
          return this.client.createOne(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.updateById)
        updateById(
          request: GrpcStorageObjectUpdateByIdRequest,
          metadata?: Metadata,
        ): GrpcStorageObject | Promise<GrpcStorageObject> | Observable<GrpcStorageObject> {
          //@ts-ignore
          return this.client.updateById(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.deleteById)
        deleteById(
          request: GrpcIdField,
          metadata?: Metadata,
        ): GrpcStorageObject | Promise<GrpcStorageObject> | Observable<GrpcStorageObject> {
          //@ts-ignore
          return this.client.deleteById(request, metadata?.clone()).pipe(...proxyPipes);
        }
      }

      return {
        Controller: GrpcStorageObjectProxyController,
        service: 'StorageObjectService',
      };
    };
  },
  ControllerMethods: (): ClassDecorator => StorageObjectServiceControllerMethods(),
} as const;
