// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/crud.proto

/* eslint-disable */

export enum LogicalOperator {
  eq = 'eq',
  ne = 'ne',
  eqs = 'eqs',
  nes = 'nes',
  lt = 'lt',
  gt = 'gt',
  lte = 'lte',
  gte = 'gte',
  in = 'in',
  nin = 'nin',
  ina = 'ina',
  nina = 'nina',
  contains = 'contains',
  ncontains = 'ncontains',
  containss = 'containss',
  ncontainss = 'ncontainss',
  between = 'between',
  nbetween = 'nbetween',
  null = 'null',
  nnull = 'nnull',
  startswith = 'startswith',
  nstartswith = 'nstartswith',
  startswiths = 'startswiths',
  nstartswiths = 'nstartswiths',
  endswith = 'endswith',
  nendswith = 'nendswith',
  endswiths = 'endswiths',
  nendswiths = 'nendswiths',
}

export enum ConditionalOperator {
  or = 'or',
  and = 'and',
}

export enum Sort {
  asc = 'asc',
  desc = 'desc',
}

export interface LogicalFilter {
  field: string;
  operator: LogicalOperator;
  string?: string;
  number?: number;
  boolean?: boolean;
}

export interface ConditionalFilter {
  key?: string;
  operator: ConditionalOperator;
  value: LogicalFilter[];
}

export interface Sorter {
  field: string;
  order: Sort;
}

export const _PACKAGE_NAME = '';
