// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { ConditionalFilter, LogicalFilter, Sorter } from './crud';

export interface Entity {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface Query {
  id?: string;
  ids: string[];
}

export interface Get {
  query: Query;
}

export interface Pagination {
  page?: number;
  limit?: number;
}

export interface GetList {
  logicalFilters: LogicalFilter[];
  conditionalFilters: ConditionalFilter[];
  sorters: Sorter[];
  pagination?: Pagination;
}

export const _PACKAGE_NAME = '';

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
