// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/user/user.messages.proto

/* eslint-disable */
import type { User, UserRole } from './user';

export interface UserQuery {
  id?: string;
  ids: string[];
  email?: string;
  roles: UserRole[];
}

export interface UserArray {
  users: User[];
}

export interface UserList {
  items: User[];
  total: number;
}

export interface UserGet {
  query?: UserQuery;
}

export interface UserCreate {
  email: string;
  password: string;
  role?: UserRole;
}

export interface UserUpdateSet {
  email?: string;
  role?: UserRole;
  password?: string;
}

export interface UserUpdate {
  set?: UserUpdateSet;
}

export interface UserUpdateById {
  id: string;
  update: UserUpdate;
}
