// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: cv/models/cv.proto

/* eslint-disable */

export interface GrpcCv {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  job: string;
  contacts: string[];
  certificates: string[];
  languages: string[];
  workExperience: string[];
  education: string[];
  personalProjects: string[];
  skills: string[];
  alias: string;
  isPrimary: boolean;
  fullName: string;
  summary: string[];
}
