// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: cv/models/education.proto

/* eslint-disable */

export interface GrpcEducation {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  title: string;
  place: string;
  city: string;
  country: string;
  startDate: Date;
  endDate?: Date;
}
