// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: auth/messages/auth.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GrpcTimestamp } from "../../google/protobuf/timestamp";
import { GrpcUser } from "../models/user";
import "server-only";

export interface GrpcAuthLogin {
  login: string;
  password: string;
}

export interface GrpcAuthMe {
  accessToken: string;
}

export interface GrpcAuthRefresh {
  refreshToken: string;
}

export interface GrpcAuthToken {
  value: string;
  expireDate: Date;
}

export interface GrpcAuthTokens {
  accessToken: GrpcAuthToken;
  refreshToken: GrpcAuthToken;
}

export interface GrpcAuthData {
  user: GrpcUser;
  tokens: GrpcAuthTokens;
}

export interface GrpcAuthStreamCode {
  code: string;
  expireDate: Date;
}

function createBaseGrpcAuthLogin(): GrpcAuthLogin {
  return { login: "", password: "" };
}

export const GrpcAuthLogin: MessageFns<GrpcAuthLogin> = {
  encode(message: GrpcAuthLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.login !== "") {
      writer.uint32(10).string(message.login);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.login = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthLogin {
    return {
      login: isSet(object.login) ? globalThis.String(object.login) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: GrpcAuthLogin): unknown {
    const obj: any = {};
    if (message.login !== "") {
      obj.login = message.login;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthLogin>, I>>(base?: I): GrpcAuthLogin {
    return GrpcAuthLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthLogin>, I>>(object: I): GrpcAuthLogin {
    const message = createBaseGrpcAuthLogin();
    message.login = object.login ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseGrpcAuthMe(): GrpcAuthMe {
  return { accessToken: "" };
}

export const GrpcAuthMe: MessageFns<GrpcAuthMe> = {
  encode(message: GrpcAuthMe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthMe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthMe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthMe {
    return { accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "" };
  },

  toJSON(message: GrpcAuthMe): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthMe>, I>>(base?: I): GrpcAuthMe {
    return GrpcAuthMe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthMe>, I>>(object: I): GrpcAuthMe {
    const message = createBaseGrpcAuthMe();
    message.accessToken = object.accessToken ?? "";
    return message;
  },
};

function createBaseGrpcAuthRefresh(): GrpcAuthRefresh {
  return { refreshToken: "" };
}

export const GrpcAuthRefresh: MessageFns<GrpcAuthRefresh> = {
  encode(message: GrpcAuthRefresh, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== "") {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthRefresh {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthRefresh();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthRefresh {
    return { refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "" };
  },

  toJSON(message: GrpcAuthRefresh): unknown {
    const obj: any = {};
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthRefresh>, I>>(base?: I): GrpcAuthRefresh {
    return GrpcAuthRefresh.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthRefresh>, I>>(object: I): GrpcAuthRefresh {
    const message = createBaseGrpcAuthRefresh();
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseGrpcAuthToken(): GrpcAuthToken {
  return { value: "", expireDate: undefined };
}

export const GrpcAuthToken: MessageFns<GrpcAuthToken> = {
  encode(message: GrpcAuthToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    if (message.expireDate !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.expireDate), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expireDate = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthToken {
    return {
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      expireDate: isSet(object.expireDate) ? fromJsonTimestamp(object.expireDate) : undefined,
    };
  },

  toJSON(message: GrpcAuthToken): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.expireDate !== undefined) {
      obj.expireDate = message.expireDate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthToken>, I>>(base?: I): GrpcAuthToken {
    return GrpcAuthToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthToken>, I>>(object: I): GrpcAuthToken {
    const message = createBaseGrpcAuthToken();
    message.value = object.value ?? "";
    message.expireDate = object.expireDate ?? undefined;
    return message;
  },
};

function createBaseGrpcAuthTokens(): GrpcAuthTokens {
  return { accessToken: undefined, refreshToken: undefined };
}

export const GrpcAuthTokens: MessageFns<GrpcAuthTokens> = {
  encode(message: GrpcAuthTokens, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== undefined) {
      GrpcAuthToken.encode(message.accessToken, writer.uint32(10).fork()).join();
    }
    if (message.refreshToken !== undefined) {
      GrpcAuthToken.encode(message.refreshToken, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthTokens {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthTokens();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = GrpcAuthToken.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = GrpcAuthToken.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthTokens {
    return {
      accessToken: isSet(object.accessToken) ? GrpcAuthToken.fromJSON(object.accessToken) : undefined,
      refreshToken: isSet(object.refreshToken) ? GrpcAuthToken.fromJSON(object.refreshToken) : undefined,
    };
  },

  toJSON(message: GrpcAuthTokens): unknown {
    const obj: any = {};
    if (message.accessToken !== undefined) {
      obj.accessToken = GrpcAuthToken.toJSON(message.accessToken);
    }
    if (message.refreshToken !== undefined) {
      obj.refreshToken = GrpcAuthToken.toJSON(message.refreshToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthTokens>, I>>(base?: I): GrpcAuthTokens {
    return GrpcAuthTokens.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthTokens>, I>>(object: I): GrpcAuthTokens {
    const message = createBaseGrpcAuthTokens();
    message.accessToken = (object.accessToken !== undefined && object.accessToken !== null)
      ? GrpcAuthToken.fromPartial(object.accessToken)
      : undefined;
    message.refreshToken = (object.refreshToken !== undefined && object.refreshToken !== null)
      ? GrpcAuthToken.fromPartial(object.refreshToken)
      : undefined;
    return message;
  },
};

function createBaseGrpcAuthData(): GrpcAuthData {
  return { user: undefined, tokens: undefined };
}

export const GrpcAuthData: MessageFns<GrpcAuthData> = {
  encode(message: GrpcAuthData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      GrpcUser.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.tokens !== undefined) {
      GrpcAuthTokens.encode(message.tokens, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = GrpcUser.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokens = GrpcAuthTokens.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthData {
    return {
      user: isSet(object.user) ? GrpcUser.fromJSON(object.user) : undefined,
      tokens: isSet(object.tokens) ? GrpcAuthTokens.fromJSON(object.tokens) : undefined,
    };
  },

  toJSON(message: GrpcAuthData): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = GrpcUser.toJSON(message.user);
    }
    if (message.tokens !== undefined) {
      obj.tokens = GrpcAuthTokens.toJSON(message.tokens);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthData>, I>>(base?: I): GrpcAuthData {
    return GrpcAuthData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthData>, I>>(object: I): GrpcAuthData {
    const message = createBaseGrpcAuthData();
    message.user = (object.user !== undefined && object.user !== null) ? GrpcUser.fromPartial(object.user) : undefined;
    message.tokens = (object.tokens !== undefined && object.tokens !== null)
      ? GrpcAuthTokens.fromPartial(object.tokens)
      : undefined;
    return message;
  },
};

function createBaseGrpcAuthStreamCode(): GrpcAuthStreamCode {
  return { code: "", expireDate: undefined };
}

export const GrpcAuthStreamCode: MessageFns<GrpcAuthStreamCode> = {
  encode(message: GrpcAuthStreamCode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.expireDate !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.expireDate), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcAuthStreamCode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcAuthStreamCode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expireDate = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcAuthStreamCode {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      expireDate: isSet(object.expireDate) ? fromJsonTimestamp(object.expireDate) : undefined,
    };
  },

  toJSON(message: GrpcAuthStreamCode): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.expireDate !== undefined) {
      obj.expireDate = message.expireDate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcAuthStreamCode>, I>>(base?: I): GrpcAuthStreamCode {
    return GrpcAuthStreamCode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcAuthStreamCode>, I>>(object: I): GrpcAuthStreamCode {
    const message = createBaseGrpcAuthStreamCode();
    message.code = object.code ?? "";
    message.expireDate = object.expireDate ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): GrpcTimestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: GrpcTimestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(GrpcTimestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
