// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: cv/models/certificate.proto

/* eslint-disable */
import { wrappers } from "protobufjs";

export interface GrpcCertificate {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  link: string;
  organization: string;
  date: Date;
}

const CV_MODELS_PACKAGE_NAME = "cv.models";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
