// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: cv/models/cv.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';

export interface GrpcCv {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  job: string;
  contacts: string[];
  certificates: string[];
  languages: string[];
  workExperience: string[];
  education: string[];
  personalProjects: string[];
  skills: string[];
  alias: string;
  isPrimary: boolean;
  fullName: string;
  summary: string[];
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
