// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/video.service.proto

/* eslint-disable */
import {
  CallOptions,
  ChannelCredentials,
  Client,
  ClientDuplexStream,
  ClientOptions,
  ClientUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  ServiceError,
} from '@grpc/grpc-js';
import { GrpcBaseQuery, GrpcGetListRequest, GrpcIdField } from '../common/service';
import { GrpcDownloadMap, GrpcUploadRequest, GrpcUrlMap } from './messages/common.messages';
import {
  GrpcVideoCreateManyRequest,
  GrpcVideoCreateManyResponse,
  GrpcVideoCreateRequest,
  GrpcVideoGetListResponse,
  GrpcVideoPopulated,
  GrpcVideoUpdateByIdRequest,
  GrpcVideoUploadResponse,
} from './messages/video.messages';
import { GrpcVideo } from './models/video';
import 'server-only';

type VideoServiceService = typeof VideoServiceService;
const VideoServiceService = {
  getUrlMap: {
    path: '/storage.VideoService/getUrlMap' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcBaseQuery): Buffer =>
      Buffer.from(GrpcBaseQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcBaseQuery => GrpcBaseQuery.decode(value),
    responseSerialize: (value: GrpcUrlMap): Buffer =>
      Buffer.from(GrpcUrlMap.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcUrlMap => GrpcUrlMap.decode(value),
  },
  getDownloadMap: {
    path: '/storage.VideoService/getDownloadMap' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcBaseQuery): Buffer =>
      Buffer.from(GrpcBaseQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcBaseQuery => GrpcBaseQuery.decode(value),
    responseSerialize: (value: GrpcDownloadMap): Buffer =>
      Buffer.from(GrpcDownloadMap.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcDownloadMap => GrpcDownloadMap.decode(value),
  },
  getById: {
    path: '/storage.VideoService/getById' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcIdField): Buffer =>
      Buffer.from(GrpcIdField.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcIdField => GrpcIdField.decode(value),
    responseSerialize: (value: GrpcVideoPopulated): Buffer =>
      Buffer.from(GrpcVideoPopulated.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideoPopulated => GrpcVideoPopulated.decode(value),
  },
  getList: {
    path: '/storage.VideoService/getList' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcGetListRequest): Buffer =>
      Buffer.from(GrpcGetListRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcGetListRequest => GrpcGetListRequest.decode(value),
    responseSerialize: (value: GrpcVideoGetListResponse): Buffer =>
      Buffer.from(GrpcVideoGetListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideoGetListResponse =>
      GrpcVideoGetListResponse.decode(value),
  },
  createOne: {
    path: '/storage.VideoService/createOne' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcVideoCreateRequest): Buffer =>
      Buffer.from(GrpcVideoCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcVideoCreateRequest =>
      GrpcVideoCreateRequest.decode(value),
    responseSerialize: (value: GrpcVideo): Buffer => Buffer.from(GrpcVideo.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideo => GrpcVideo.decode(value),
  },
  createMany: {
    path: '/storage.VideoService/createMany' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcVideoCreateManyRequest): Buffer =>
      Buffer.from(GrpcVideoCreateManyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcVideoCreateManyRequest =>
      GrpcVideoCreateManyRequest.decode(value),
    responseSerialize: (value: GrpcVideoCreateManyResponse): Buffer =>
      Buffer.from(GrpcVideoCreateManyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideoCreateManyResponse =>
      GrpcVideoCreateManyResponse.decode(value),
  },
  updateById: {
    path: '/storage.VideoService/updateById' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcVideoUpdateByIdRequest): Buffer =>
      Buffer.from(GrpcVideoUpdateByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcVideoUpdateByIdRequest =>
      GrpcVideoUpdateByIdRequest.decode(value),
    responseSerialize: (value: GrpcVideo): Buffer => Buffer.from(GrpcVideo.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideo => GrpcVideo.decode(value),
  },
  uploadOne: {
    path: '/storage.VideoService/uploadOne' as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: GrpcUploadRequest): Buffer =>
      Buffer.from(GrpcUploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcUploadRequest => GrpcUploadRequest.decode(value),
    responseSerialize: (value: GrpcVideoUploadResponse): Buffer =>
      Buffer.from(GrpcVideoUploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideoUploadResponse =>
      GrpcVideoUploadResponse.decode(value),
  },
  deleteById: {
    path: '/storage.VideoService/deleteById' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcIdField): Buffer =>
      Buffer.from(GrpcIdField.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcIdField => GrpcIdField.decode(value),
    responseSerialize: (value: GrpcVideo): Buffer => Buffer.from(GrpcVideo.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcVideo => GrpcVideo.decode(value),
  },
} as const;

export interface GrpcVideoServiceClient extends Client {
  getUrlMap(
    request: GrpcBaseQuery,
    callback: (error: ServiceError | null, response: GrpcUrlMap) => void,
  ): ClientUnaryCall;
  getUrlMap(
    request: GrpcBaseQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcUrlMap) => void,
  ): ClientUnaryCall;
  getUrlMap(
    request: GrpcBaseQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcUrlMap) => void,
  ): ClientUnaryCall;
  getDownloadMap(
    request: GrpcBaseQuery,
    callback: (error: ServiceError | null, response: GrpcDownloadMap) => void,
  ): ClientUnaryCall;
  getDownloadMap(
    request: GrpcBaseQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcDownloadMap) => void,
  ): ClientUnaryCall;
  getDownloadMap(
    request: GrpcBaseQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcDownloadMap) => void,
  ): ClientUnaryCall;
  getById(
    request: GrpcIdField,
    callback: (error: ServiceError | null, response: GrpcVideoPopulated) => void,
  ): ClientUnaryCall;
  getById(
    request: GrpcIdField,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideoPopulated) => void,
  ): ClientUnaryCall;
  getById(
    request: GrpcIdField,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideoPopulated) => void,
  ): ClientUnaryCall;
  getList(
    request: GrpcGetListRequest,
    callback: (error: ServiceError | null, response: GrpcVideoGetListResponse) => void,
  ): ClientUnaryCall;
  getList(
    request: GrpcGetListRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideoGetListResponse) => void,
  ): ClientUnaryCall;
  getList(
    request: GrpcGetListRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideoGetListResponse) => void,
  ): ClientUnaryCall;
  createOne(
    request: GrpcVideoCreateRequest,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  createOne(
    request: GrpcVideoCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  createOne(
    request: GrpcVideoCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  createMany(
    request: GrpcVideoCreateManyRequest,
    callback: (error: ServiceError | null, response: GrpcVideoCreateManyResponse) => void,
  ): ClientUnaryCall;
  createMany(
    request: GrpcVideoCreateManyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideoCreateManyResponse) => void,
  ): ClientUnaryCall;
  createMany(
    request: GrpcVideoCreateManyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideoCreateManyResponse) => void,
  ): ClientUnaryCall;
  updateById(
    request: GrpcVideoUpdateByIdRequest,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  updateById(
    request: GrpcVideoUpdateByIdRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  updateById(
    request: GrpcVideoUpdateByIdRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  uploadOne(): ClientDuplexStream<GrpcUploadRequest, GrpcVideoUploadResponse>;
  uploadOne(
    options: Partial<CallOptions>,
  ): ClientDuplexStream<GrpcUploadRequest, GrpcVideoUploadResponse>;
  uploadOne(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<GrpcUploadRequest, GrpcVideoUploadResponse>;
  deleteById(
    request: GrpcIdField,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  deleteById(
    request: GrpcIdField,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
  deleteById(
    request: GrpcIdField,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcVideo) => void,
  ): ClientUnaryCall;
}

export const GrpcVideoServiceClient = makeGenericClientConstructor(
  VideoServiceService,
  'storage.VideoService',
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): GrpcVideoServiceClient;
  service: {
    readonly getUrlMap: {
      readonly path: '/storage.VideoService/getUrlMap';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcBaseQuery) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcBaseQuery;
      readonly responseSerialize: (value: GrpcUrlMap) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcUrlMap;
    };
    readonly getDownloadMap: {
      readonly path: '/storage.VideoService/getDownloadMap';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcBaseQuery) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcBaseQuery;
      readonly responseSerialize: (value: GrpcDownloadMap) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcDownloadMap;
    };
    readonly getById: {
      readonly path: '/storage.VideoService/getById';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcIdField) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcIdField;
      readonly responseSerialize: (value: GrpcVideoPopulated) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideoPopulated;
    };
    readonly getList: {
      readonly path: '/storage.VideoService/getList';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcGetListRequest) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcGetListRequest;
      readonly responseSerialize: (value: GrpcVideoGetListResponse) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideoGetListResponse;
    };
    readonly createOne: {
      readonly path: '/storage.VideoService/createOne';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcVideoCreateRequest) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcVideoCreateRequest;
      readonly responseSerialize: (value: GrpcVideo) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideo;
    };
    readonly createMany: {
      readonly path: '/storage.VideoService/createMany';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcVideoCreateManyRequest) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcVideoCreateManyRequest;
      readonly responseSerialize: (value: GrpcVideoCreateManyResponse) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideoCreateManyResponse;
    };
    readonly updateById: {
      readonly path: '/storage.VideoService/updateById';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcVideoUpdateByIdRequest) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcVideoUpdateByIdRequest;
      readonly responseSerialize: (value: GrpcVideo) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideo;
    };
    readonly uploadOne: {
      readonly path: '/storage.VideoService/uploadOne';
      readonly requestStream: true;
      readonly responseStream: true;
      readonly requestSerialize: (value: GrpcUploadRequest) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcUploadRequest;
      readonly responseSerialize: (value: GrpcVideoUploadResponse) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideoUploadResponse;
    };
    readonly deleteById: {
      readonly path: '/storage.VideoService/deleteById';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcIdField) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcIdField;
      readonly responseSerialize: (value: GrpcVideo) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcVideo;
    };
  };
  serviceName: string;
};

export class GrpcVideoRepository {
  protected readonly client: GrpcVideoServiceClient;

  constructor(
    address: string,
    credentials: ChannelCredentials = ChannelCredentials.createInsecure(),
    options?: Partial<ClientOptions>,
  ) {
    this.client = new GrpcVideoServiceClient(address, credentials, options);
  }

  getClient(): GrpcVideoServiceClient {
    return this.client;
  }

  getUrlMap(
    request: GrpcBaseQuery,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcUrlMap> {
    return new Promise<GrpcUrlMap>((resolve, reject) => {
      this.client.getUrlMap(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  getDownloadMap(
    request: GrpcBaseQuery,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcDownloadMap> {
    return new Promise<GrpcDownloadMap>((resolve, reject) => {
      this.client.getDownloadMap(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  getById(
    request: GrpcIdField,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideoPopulated> {
    return new Promise<GrpcVideoPopulated>((resolve, reject) => {
      this.client.getById(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  getList(
    request: GrpcGetListRequest,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideoGetListResponse> {
    return new Promise<GrpcVideoGetListResponse>((resolve, reject) => {
      this.client.getList(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  createOne(
    request: GrpcVideoCreateRequest,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideo> {
    return new Promise<GrpcVideo>((resolve, reject) => {
      this.client.createOne(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  createMany(
    request: GrpcVideoCreateManyRequest,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideoCreateManyResponse> {
    return new Promise<GrpcVideoCreateManyResponse>((resolve, reject) => {
      this.client.createMany(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  updateById(
    request: GrpcVideoUpdateByIdRequest,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideo> {
    return new Promise<GrpcVideo>((resolve, reject) => {
      this.client.updateById(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  deleteById(
    request: GrpcIdField,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcVideo> {
    return new Promise<GrpcVideo>((resolve, reject) => {
      this.client.deleteById(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }
}
