// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: cv/models/experience.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import {
  GrpcEmployeeRole,
  grpcEmployeeRoleFromJSON,
  grpcEmployeeRoleToJSON,
  grpcEmployeeRoleToNumber,
} from '../../common/enums';
import { GrpcTimestamp } from '../../google/protobuf/timestamp';
import 'server-only';

export interface GrpcExperience {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  projects: string[];
  company: string;
  position: string;
  domain: string;
  role: GrpcEmployeeRole;
  isPublic: boolean;
  startDate: Date;
  endDate?: Date;
}

function createBaseGrpcExperience(): GrpcExperience {
  return {
    id: '',
    createdAt: undefined,
    updatedAt: undefined,
    projects: [],
    company: '',
    position: '',
    domain: '',
    role: GrpcEmployeeRole.BACKEND_DEVELOPER,
    isPublic: false,
    startDate: undefined,
    endDate: undefined,
  };
}

export const GrpcExperience: MessageFns<GrpcExperience> = {
  encode(message: GrpcExperience, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.createdAt !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.createdAt), writer.uint32(18).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).join();
    }
    for (const v of message.projects) {
      writer.uint32(34).string(v!);
    }
    if (message.company !== '') {
      writer.uint32(42).string(message.company);
    }
    if (message.position !== '') {
      writer.uint32(50).string(message.position);
    }
    if (message.domain !== '') {
      writer.uint32(58).string(message.domain);
    }
    if (message.role !== GrpcEmployeeRole.BACKEND_DEVELOPER) {
      writer.uint32(64).int32(grpcEmployeeRoleToNumber(message.role));
    }
    if (message.isPublic !== false) {
      writer.uint32(72).bool(message.isPublic);
    }
    if (message.startDate !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.startDate), writer.uint32(82).fork()).join();
    }
    if (message.endDate !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.endDate), writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcExperience {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcExperience();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.projects.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.company = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.position = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.role = grpcEmployeeRoleFromJSON(reader.int32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.startDate = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.endDate = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcExperience {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
      projects: globalThis.Array.isArray(object?.projects)
        ? object.projects.map((e: any) => globalThis.String(e))
        : [],
      company: isSet(object.company) ? globalThis.String(object.company) : '',
      position: isSet(object.position) ? globalThis.String(object.position) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
      role: isSet(object.role)
        ? grpcEmployeeRoleFromJSON(object.role)
        : GrpcEmployeeRole.BACKEND_DEVELOPER,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
      startDate: isSet(object.startDate) ? fromJsonTimestamp(object.startDate) : undefined,
      endDate: isSet(object.endDate) ? fromJsonTimestamp(object.endDate) : undefined,
    };
  },

  toJSON(message: GrpcExperience): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.projects?.length) {
      obj.projects = message.projects;
    }
    if (message.company !== '') {
      obj.company = message.company;
    }
    if (message.position !== '') {
      obj.position = message.position;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    if (message.role !== GrpcEmployeeRole.BACKEND_DEVELOPER) {
      obj.role = grpcEmployeeRoleToJSON(message.role);
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.startDate !== undefined) {
      obj.startDate = message.startDate.toISOString();
    }
    if (message.endDate !== undefined) {
      obj.endDate = message.endDate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcExperience>, I>>(base?: I): GrpcExperience {
    return GrpcExperience.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcExperience>, I>>(object: I): GrpcExperience {
    const message = createBaseGrpcExperience();
    message.id = object.id ?? '';
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.projects = object.projects?.map((e) => e) || [];
    message.company = object.company ?? '';
    message.position = object.position ?? '';
    message.domain = object.domain ?? '';
    message.role = object.role ?? GrpcEmployeeRole.BACKEND_DEVELOPER;
    message.isPublic = object.isPublic ?? false;
    message.startDate = object.startDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): GrpcTimestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: GrpcTimestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(GrpcTimestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
