name: base

services:
#  mongo:
#    image: mongo:latest
#    restart: unless-stopped
#    container_name: base-mongo
#    networks:
#      - private_network
#    ports:
#      - '27017:27017'
#    volumes:
#      - mongo_data:/data/db
#    profiles:
#      - local
#      - all

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: base-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      sh -c "docker-entrypoint.sh postgres &
      sleep 5;
      psql -U admin -d postgres -c 'CREATE DATABASE auth;';
      psql -U admin -d postgres -c 'CREATE DATABASE storage;';
      wait"
    networks:
      - private_network
      - public_network
    profiles:
      - local
      - all

  postgres-ui:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: base-postgres-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: string123
    ports:
      - "8080:80"
    networks:
      - private_network
      - public_network
    depends_on:
      - postgres
    profiles:
      - local
      - all

#  redis:
#    image: redis:latest
#    restart: unless-stopped
#    container_name: base-redis
#    command: redis-server --appendonly yes
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis_data:/data
#    networks:
#      - private_network
#      - public_network
#    profiles:
#      - local
#      - all
#
#  redis-ui:
#    image: redis/redisinsight:latest
#    container_name: base-redis-ui
#    environment:
#      REDIS_HOSTS: local:redis:6379
#    ports:
#      - "5540:5540"
#    networks:
#      - private_network
#      - public_network
#    depends_on:
#      - redis
#    profiles:
#      - local
#      - all

  backend.auth:
    build:
      context: .
      dockerfile: ./backend/apps/auth/Dockerfile
    restart: unless-stopped
    container_name: base-backend-auth
    ports:
      - '8001:8001'
    environment:
      PORT: 8001
      NODE_ENV: production
      DATABASE_URL: postgresql://admin:password123@postgres:5432
      AUTH_GRPC_URL: 0.0.0.0:8001
      ACCESS_JWT_SECRET: string123
      REFRESH_JWT_SECRET: string123
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: string123
    networks:
      - private_network
    depends_on:
      - mongo
    profiles:
      - all

  backend.api-gateway:
    build:
      context: .
      dockerfile: ./backend/apps/api-gateway/Dockerfile
    restart: unless-stopped
    container_name: base-backend-api-gateway
    ports:
      - '${BACKEND_PORT:-5555}:5555'
    environment:
      PORT: 5555
      NODE_ENV: production
      API_GATEWAY_GRPC_URL: 0.0.0.0:8000
      AUTH_GRPC_URL: backend.auth:8001
    networks:
      - private_network
      - public_network
    depends_on:
      - backend.auth
    profiles:
      - all

  frontend.admin:
    build:
      context: .
      dockerfile: ./frontend/apps/admin/Dockerfile
    restart: unless-stopped
    container_name: base-frontend-admin
    ports:
      - '${ADMIN_PORT:-3336}:3336'
    environment:
      PORT: 3336
      HOSTNAME: 0.0.0.0
      NODE_ENV: production
      BACKEND_GRPC_URL: backend.api-gateway:8000
      DEFAULT_EMAIL: admin@gmail.com
      DEFAULT_PASSWORD: string123
      CHUNK_SIZE_MB: 1
    networks:
      - private_network
      - public_network
    depends_on:
      - mongo
      - backend.api-gateway
    profiles:
      - all

networks:
  private_network:
  public_network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
  redis_data:
