export const NATS_CONFIG_SERVICE = Symbol('NATS_CONFIG_SERVICE');
export const NATS_MICROSERVICE_OPTIONS = Symbol('NATS_MICROSERVICE_OPTIONS');
export const NATS_CLIENT = Symbol('NATS_GLOBAL_CLIENT');
