// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: common/fields.proto

/* eslint-disable */

export interface IdField {
  id: string;
}

export interface IdsField {
  ids: string[];
}

export interface UserIdField {
  userId: string;
}

export interface UserField {
  user: string;
}
