// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/service.proto

/* eslint-disable */
import type { CrudConditionalFilter, CrudLogicalFilter, CrudSorter } from './crud';

export interface IdField {
  id: string;
}

export interface IdsField {
  ids: string[];
}

export interface EntityWithTimestamps {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface BaseQuery {
  id?: string;
  ids: string[];
}

export interface BaseRequest {
  query: BaseQuery;
}

export interface Pagination {
  page?: number;
  limit?: number;
}

export interface GetListRequest {
  logicalFilters: CrudLogicalFilter[];
  conditionalFilters: CrudConditionalFilter[];
  sorters: CrudSorter[];
  pagination?: Pagination;
}

export interface BooleanResult {
  value: boolean;
}
