// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: common/types.proto

/* eslint-disable */

export interface Boolean {
  value: boolean;
}

export interface StringMap {
  entries: Map<string, string>;
}

export interface StringMap_EntriesEntry {
  key: string;
  value: string;
}

export interface StringArray {
  items: string[];
}
