// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/models/storage-object.proto

/* eslint-disable */

export enum StorageObjectType {
  FOLDER = 'FOLDER',
  FILE = 'FILE',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export interface StorageObject {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: StorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
}
