// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/messages/common.messages.proto

/* eslint-disable */

export interface DownloadData {
  url: string;
  fileName: string;
}

export interface UrlMap {
  items: { [key: string]: string };
}

export interface UrlMapItemsEntry {
  key: string;
  value: string;
}

export interface DownloadMap {
  items: { [key: string]: DownloadData };
}

export interface DownloadMapItemsEntry {
  key: string;
  value: DownloadData;
}

export interface UploadRequest {
  id?: string;
  chunk?: Uint8Array<ArrayBufferLike>;
}
