// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/messages/file.messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { File, FileUploadStatus } from '../models/file';
import { StorageObjectManyMetadata, StorageObjectMetadata } from './storage-object.messages';

export interface FileQuery {
  id?: string;
  ids: string[];
  mimeType?: string;
  mimeTypes: string[];
  userId?: string;
  userIds: string[];
  extension?: string;
  uploadStatus?: FileUploadStatus;
  uploadStatuses: FileUploadStatus[];
  createdAfter?: Date;
}

export interface FileRequest {
  query: FileQuery;
}

export interface FileGetListResponse {
  items: File[];
  total: number;
}

export interface FileCreate {
  originalName: string;
  size: number;
  mimeType: string;
}

export interface FileCreateRequest {
  file: FileCreate;
  storage?: StorageObjectMetadata;
}

export interface FileCreateManyItem {
  file: FileCreate;
  uploadId: string;
}

export interface FileCreateManyRequest {
  storage?: StorageObjectManyMetadata;
  items: FileCreateManyItem[];
}

export interface FileCreateManyResponse {
  items: File[];
}

export interface FileUploadResponse {
  entity?: File;
  canSendChunks?: boolean;
  ack?: boolean;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
