// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/messages/storage-object.messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { BaseQuery } from '../../common/service';
import { File } from '../models/file';
import { Image } from '../models/image';
import { StorageObjectType } from '../models/storage-object';
import { Video } from '../models/video';

export interface StorageObjectPopulated {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: StorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  file?: File;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  image?: Image;
  video?: Video;
}

export interface StorageObjectQuery {
  id?: string;
  ids: string[];
  type?: StorageObjectType;
  userId?: string;
  isPublic?: boolean;
  parent?: string;
  file?: string;
  name?: string;
}

export interface StorageObjectRequest {
  query: StorageObjectQuery;
}

export interface StorageObjectList {
  items: StorageObjectPopulated[];
}

export interface StorageObjectGetListResponse {
  items: StorageObjectPopulated[];
  total: number;
}

export interface StorageObjectExistsFolderRequest {
  parent: string;
  name: string;
}

export interface StorageObjectGetFoldersRequest {
  id?: string;
}

export interface StorageObjectGetFoldersItem {
  id: string;
  folderPath: string;
}

export interface StorageObjectGetFoldersResponse {
  items: StorageObjectGetFoldersItem[];
}

export interface StorageObjectCreate {
  name: string;
  isPublic: boolean;
  parent?: string;
  type: StorageObjectType;
  file?: string;
  image?: string;
  video?: string;
}

export interface StorageObjectMetadata {
  name: string;
  isPublic: boolean;
  parent: string;
}

export interface StorageObjectManyMetadata {
  isPublic: boolean;
  parent: string;
}

export interface StorageObjectUpdateSet {
  name?: string;
  isPublic?: boolean;
  parent?: string;
}

export interface StorageObjectUpdate {
  set?: StorageObjectUpdateSet;
}

export interface StorageObjectUpdateRequest {
  query: BaseQuery;
  update: StorageObjectUpdate;
}

export interface StorageObjectUpdateByIdRequest {
  id: string;
  update: StorageObjectUpdate;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
