export const NATS_MICROSERVICE_OPTIONS = Symbol('NATS_MICROSERVICE_OPTIONS');
export const NATS_CONNECTION = Symbol('NATS_CONNECTION');
export const NATS_CLIENT = Symbol('NATS_CLIENT');
export const NATS_STREAM_PROVISIONER = Symbol('NATS_STREAM_PROVISIONER');
