// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: storage/messages/storage-object.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GrpcBaseQuery } from "../../common/service";
import { GrpcTimestamp } from "../../google/protobuf/timestamp";
import { GrpcFile } from "../models/file";
import { GrpcImage } from "../models/image";
import {
    GrpcStorageObjectType,
    grpcStorageObjectTypeFromJSON,
    grpcStorageObjectTypeToJSON,
    grpcStorageObjectTypeToNumber,
} from "../models/storage-object";
import { GrpcVideo } from "../models/video";
import "server-only";

export interface GrpcStorageObjectPopulated {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: GrpcStorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  file?: GrpcFile;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  image?: GrpcImage;
  video?: GrpcVideo;
}

export interface GrpcStorageObjectQuery {
  id?: string;
  ids: string[];
  type?: GrpcStorageObjectType;
  userId?: string;
  isPublic?: boolean;
  parent?: string;
  file?: string;
  name?: string;
}

export interface GrpcStorageObjectRequest {
  query: GrpcStorageObjectQuery;
}

export interface GrpcStorageObjectList {
  items: GrpcStorageObjectPopulated[];
}

export interface GrpcStorageObjectGetListResponse {
  items: GrpcStorageObjectPopulated[];
  total: number;
}

export interface GrpcStorageObjectExistsFolderRequest {
  parent: string;
  name: string;
}

export interface GrpcStorageObjectGetFoldersRequest {
  id?: string;
}

export interface GrpcStorageObjectGetFoldersItem {
  id: string;
  folderPath: string;
}

export interface GrpcStorageObjectGetFoldersResponse {
  items: GrpcStorageObjectGetFoldersItem[];
}

export interface GrpcStorageObjectCreate {
  name: string;
  isPublic: boolean;
  parent?: string;
  type: GrpcStorageObjectType;
  file?: string;
  image?: string;
  video?: string;
}

export interface GrpcStorageObjectMetadata {
  name: string;
  isPublic: boolean;
  parent: string;
}

export interface GrpcStorageObjectManyMetadata {
  isPublic: boolean;
  parent: string;
}

export interface GrpcStorageObjectUpdateSet {
  name?: string;
  isPublic?: boolean;
  parent?: string;
}

export interface GrpcStorageObjectUpdate {
  set?: GrpcStorageObjectUpdateSet;
}

export interface GrpcStorageObjectUpdateRequest {
  query: GrpcBaseQuery;
  update: GrpcStorageObjectUpdate;
}

export interface GrpcStorageObjectUpdateByIdRequest {
  id: string;
  update: GrpcStorageObjectUpdate;
}

function createBaseGrpcStorageObjectPopulated(): GrpcStorageObjectPopulated {
  return {
    id: "",
    createdAt: undefined,
    updatedAt: undefined,
    name: "",
    isPublic: false,
    isFolder: false,
    type: GrpcStorageObjectType.FOLDER,
    userId: "",
    fileId: undefined,
    parentId: undefined,
    file: undefined,
    folderPath: undefined,
    imageId: undefined,
    videoId: undefined,
    image: undefined,
    video: undefined,
  };
}

export const GrpcStorageObjectPopulated: MessageFns<GrpcStorageObjectPopulated> = {
  encode(message: GrpcStorageObjectPopulated, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.createdAt !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.createdAt), writer.uint32(18).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      GrpcTimestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.isPublic !== false) {
      writer.uint32(40).bool(message.isPublic);
    }
    if (message.isFolder !== false) {
      writer.uint32(48).bool(message.isFolder);
    }
    if (message.type !== GrpcStorageObjectType.FOLDER) {
      writer.uint32(56).int32(grpcStorageObjectTypeToNumber(message.type));
    }
    if (message.userId !== "") {
      writer.uint32(66).string(message.userId);
    }
    if (message.fileId !== undefined) {
      writer.uint32(74).string(message.fileId);
    }
    if (message.parentId !== undefined) {
      writer.uint32(82).string(message.parentId);
    }
    if (message.file !== undefined) {
      GrpcFile.encode(message.file, writer.uint32(90).fork()).join();
    }
    if (message.folderPath !== undefined) {
      writer.uint32(98).string(message.folderPath);
    }
    if (message.imageId !== undefined) {
      writer.uint32(106).string(message.imageId);
    }
    if (message.videoId !== undefined) {
      writer.uint32(114).string(message.videoId);
    }
    if (message.image !== undefined) {
      GrpcImage.encode(message.image, writer.uint32(122).fork()).join();
    }
    if (message.video !== undefined) {
      GrpcVideo.encode(message.video, writer.uint32(130).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectPopulated {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectPopulated();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(GrpcTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isFolder = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.type = grpcStorageObjectTypeFromJSON(reader.int32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.fileId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.file = GrpcFile.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.folderPath = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.imageId = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.videoId = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.image = GrpcImage.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.video = GrpcVideo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectPopulated {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
      isFolder: isSet(object.isFolder) ? globalThis.Boolean(object.isFolder) : false,
      type: isSet(object.type) ? grpcStorageObjectTypeFromJSON(object.type) : GrpcStorageObjectType.FOLDER,
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      fileId: isSet(object.fileId) ? globalThis.String(object.fileId) : undefined,
      parentId: isSet(object.parentId) ? globalThis.String(object.parentId) : undefined,
      file: isSet(object.file) ? GrpcFile.fromJSON(object.file) : undefined,
      folderPath: isSet(object.folderPath) ? globalThis.String(object.folderPath) : undefined,
      imageId: isSet(object.imageId) ? globalThis.String(object.imageId) : undefined,
      videoId: isSet(object.videoId) ? globalThis.String(object.videoId) : undefined,
      image: isSet(object.image) ? GrpcImage.fromJSON(object.image) : undefined,
      video: isSet(object.video) ? GrpcVideo.fromJSON(object.video) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectPopulated): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.isFolder !== false) {
      obj.isFolder = message.isFolder;
    }
    if (message.type !== GrpcStorageObjectType.FOLDER) {
      obj.type = grpcStorageObjectTypeToJSON(message.type);
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.fileId !== undefined) {
      obj.fileId = message.fileId;
    }
    if (message.parentId !== undefined) {
      obj.parentId = message.parentId;
    }
    if (message.file !== undefined) {
      obj.file = GrpcFile.toJSON(message.file);
    }
    if (message.folderPath !== undefined) {
      obj.folderPath = message.folderPath;
    }
    if (message.imageId !== undefined) {
      obj.imageId = message.imageId;
    }
    if (message.videoId !== undefined) {
      obj.videoId = message.videoId;
    }
    if (message.image !== undefined) {
      obj.image = GrpcImage.toJSON(message.image);
    }
    if (message.video !== undefined) {
      obj.video = GrpcVideo.toJSON(message.video);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectPopulated>, I>>(base?: I): GrpcStorageObjectPopulated {
    return GrpcStorageObjectPopulated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectPopulated>, I>>(object: I): GrpcStorageObjectPopulated {
    const message = createBaseGrpcStorageObjectPopulated();
    message.id = object.id ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.name = object.name ?? "";
    message.isPublic = object.isPublic ?? false;
    message.isFolder = object.isFolder ?? false;
    message.type = object.type ?? GrpcStorageObjectType.FOLDER;
    message.userId = object.userId ?? "";
    message.fileId = object.fileId ?? undefined;
    message.parentId = object.parentId ?? undefined;
    message.file = (object.file !== undefined && object.file !== null) ? GrpcFile.fromPartial(object.file) : undefined;
    message.folderPath = object.folderPath ?? undefined;
    message.imageId = object.imageId ?? undefined;
    message.videoId = object.videoId ?? undefined;
    message.image = (object.image !== undefined && object.image !== null)
      ? GrpcImage.fromPartial(object.image)
      : undefined;
    message.video = (object.video !== undefined && object.video !== null)
      ? GrpcVideo.fromPartial(object.video)
      : undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectQuery(): GrpcStorageObjectQuery {
  return {
    id: undefined,
    ids: [],
    type: undefined,
    userId: undefined,
    isPublic: undefined,
    parent: undefined,
    file: undefined,
    name: undefined,
  };
}

export const GrpcStorageObjectQuery: MessageFns<GrpcStorageObjectQuery> = {
  encode(message: GrpcStorageObjectQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    if (message.type !== undefined) {
      writer.uint32(24).int32(grpcStorageObjectTypeToNumber(message.type));
    }
    if (message.userId !== undefined) {
      writer.uint32(34).string(message.userId);
    }
    if (message.isPublic !== undefined) {
      writer.uint32(40).bool(message.isPublic);
    }
    if (message.parent !== undefined) {
      writer.uint32(50).string(message.parent);
    }
    if (message.file !== undefined) {
      writer.uint32(58).string(message.file);
    }
    if (message.name !== undefined) {
      writer.uint32(66).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = grpcStorageObjectTypeFromJSON(reader.int32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectQuery {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      ids: globalThis.Array.isArray(object?.ids) ? object.ids.map((e: any) => globalThis.String(e)) : [],
      type: isSet(object.type) ? grpcStorageObjectTypeFromJSON(object.type) : undefined,
      userId: isSet(object.userId) ? globalThis.String(object.userId) : undefined,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : undefined,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : undefined,
      file: isSet(object.file) ? globalThis.String(object.file) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectQuery): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    if (message.type !== undefined) {
      obj.type = grpcStorageObjectTypeToJSON(message.type);
    }
    if (message.userId !== undefined) {
      obj.userId = message.userId;
    }
    if (message.isPublic !== undefined) {
      obj.isPublic = message.isPublic;
    }
    if (message.parent !== undefined) {
      obj.parent = message.parent;
    }
    if (message.file !== undefined) {
      obj.file = message.file;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectQuery>, I>>(base?: I): GrpcStorageObjectQuery {
    return GrpcStorageObjectQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectQuery>, I>>(object: I): GrpcStorageObjectQuery {
    const message = createBaseGrpcStorageObjectQuery();
    message.id = object.id ?? undefined;
    message.ids = object.ids?.map((e) => e) || [];
    message.type = object.type ?? undefined;
    message.userId = object.userId ?? undefined;
    message.isPublic = object.isPublic ?? undefined;
    message.parent = object.parent ?? undefined;
    message.file = object.file ?? undefined;
    message.name = object.name ?? undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectRequest(): GrpcStorageObjectRequest {
  return { query: undefined };
}

export const GrpcStorageObjectRequest: MessageFns<GrpcStorageObjectRequest> = {
  encode(message: GrpcStorageObjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      GrpcStorageObjectQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = GrpcStorageObjectQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectRequest {
    return { query: isSet(object.query) ? GrpcStorageObjectQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: GrpcStorageObjectRequest): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = GrpcStorageObjectQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectRequest>, I>>(base?: I): GrpcStorageObjectRequest {
    return GrpcStorageObjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectRequest>, I>>(object: I): GrpcStorageObjectRequest {
    const message = createBaseGrpcStorageObjectRequest();
    message.query = (object.query !== undefined && object.query !== null)
      ? GrpcStorageObjectQuery.fromPartial(object.query)
      : undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectList(): GrpcStorageObjectList {
  return { items: [] };
}

export const GrpcStorageObjectList: MessageFns<GrpcStorageObjectList> = {
  encode(message: GrpcStorageObjectList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      GrpcStorageObjectPopulated.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(GrpcStorageObjectPopulated.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectList {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => GrpcStorageObjectPopulated.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GrpcStorageObjectList): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => GrpcStorageObjectPopulated.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectList>, I>>(base?: I): GrpcStorageObjectList {
    return GrpcStorageObjectList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectList>, I>>(object: I): GrpcStorageObjectList {
    const message = createBaseGrpcStorageObjectList();
    message.items = object.items?.map((e) => GrpcStorageObjectPopulated.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrpcStorageObjectGetListResponse(): GrpcStorageObjectGetListResponse {
  return { items: [], total: 0 };
}

export const GrpcStorageObjectGetListResponse: MessageFns<GrpcStorageObjectGetListResponse> = {
  encode(message: GrpcStorageObjectGetListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      GrpcStorageObjectPopulated.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectGetListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectGetListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(GrpcStorageObjectPopulated.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectGetListResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => GrpcStorageObjectPopulated.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: GrpcStorageObjectGetListResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => GrpcStorageObjectPopulated.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectGetListResponse>, I>>(
    base?: I,
  ): GrpcStorageObjectGetListResponse {
    return GrpcStorageObjectGetListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectGetListResponse>, I>>(
    object: I,
  ): GrpcStorageObjectGetListResponse {
    const message = createBaseGrpcStorageObjectGetListResponse();
    message.items = object.items?.map((e) => GrpcStorageObjectPopulated.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseGrpcStorageObjectExistsFolderRequest(): GrpcStorageObjectExistsFolderRequest {
  return { parent: "", name: "" };
}

export const GrpcStorageObjectExistsFolderRequest: MessageFns<GrpcStorageObjectExistsFolderRequest> = {
  encode(message: GrpcStorageObjectExistsFolderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectExistsFolderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectExistsFolderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectExistsFolderRequest {
    return {
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: GrpcStorageObjectExistsFolderRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectExistsFolderRequest>, I>>(
    base?: I,
  ): GrpcStorageObjectExistsFolderRequest {
    return GrpcStorageObjectExistsFolderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectExistsFolderRequest>, I>>(
    object: I,
  ): GrpcStorageObjectExistsFolderRequest {
    const message = createBaseGrpcStorageObjectExistsFolderRequest();
    message.parent = object.parent ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseGrpcStorageObjectGetFoldersRequest(): GrpcStorageObjectGetFoldersRequest {
  return { id: undefined };
}

export const GrpcStorageObjectGetFoldersRequest: MessageFns<GrpcStorageObjectGetFoldersRequest> = {
  encode(message: GrpcStorageObjectGetFoldersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectGetFoldersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectGetFoldersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectGetFoldersRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : undefined };
  },

  toJSON(message: GrpcStorageObjectGetFoldersRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersRequest>, I>>(
    base?: I,
  ): GrpcStorageObjectGetFoldersRequest {
    return GrpcStorageObjectGetFoldersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersRequest>, I>>(
    object: I,
  ): GrpcStorageObjectGetFoldersRequest {
    const message = createBaseGrpcStorageObjectGetFoldersRequest();
    message.id = object.id ?? undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectGetFoldersItem(): GrpcStorageObjectGetFoldersItem {
  return { id: "", folderPath: "" };
}

export const GrpcStorageObjectGetFoldersItem: MessageFns<GrpcStorageObjectGetFoldersItem> = {
  encode(message: GrpcStorageObjectGetFoldersItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.folderPath !== "") {
      writer.uint32(18).string(message.folderPath);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectGetFoldersItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectGetFoldersItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.folderPath = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectGetFoldersItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      folderPath: isSet(object.folderPath) ? globalThis.String(object.folderPath) : "",
    };
  },

  toJSON(message: GrpcStorageObjectGetFoldersItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.folderPath !== "") {
      obj.folderPath = message.folderPath;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersItem>, I>>(base?: I): GrpcStorageObjectGetFoldersItem {
    return GrpcStorageObjectGetFoldersItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersItem>, I>>(
    object: I,
  ): GrpcStorageObjectGetFoldersItem {
    const message = createBaseGrpcStorageObjectGetFoldersItem();
    message.id = object.id ?? "";
    message.folderPath = object.folderPath ?? "";
    return message;
  },
};

function createBaseGrpcStorageObjectGetFoldersResponse(): GrpcStorageObjectGetFoldersResponse {
  return { items: [] };
}

export const GrpcStorageObjectGetFoldersResponse: MessageFns<GrpcStorageObjectGetFoldersResponse> = {
  encode(message: GrpcStorageObjectGetFoldersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      GrpcStorageObjectGetFoldersItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectGetFoldersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectGetFoldersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(GrpcStorageObjectGetFoldersItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectGetFoldersResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => GrpcStorageObjectGetFoldersItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GrpcStorageObjectGetFoldersResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => GrpcStorageObjectGetFoldersItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersResponse>, I>>(
    base?: I,
  ): GrpcStorageObjectGetFoldersResponse {
    return GrpcStorageObjectGetFoldersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectGetFoldersResponse>, I>>(
    object: I,
  ): GrpcStorageObjectGetFoldersResponse {
    const message = createBaseGrpcStorageObjectGetFoldersResponse();
    message.items = object.items?.map((e) => GrpcStorageObjectGetFoldersItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrpcStorageObjectCreate(): GrpcStorageObjectCreate {
  return {
    name: "",
    isPublic: false,
    parent: undefined,
    type: GrpcStorageObjectType.FOLDER,
    file: undefined,
    image: undefined,
    video: undefined,
  };
}

export const GrpcStorageObjectCreate: MessageFns<GrpcStorageObjectCreate> = {
  encode(message: GrpcStorageObjectCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.isPublic !== false) {
      writer.uint32(16).bool(message.isPublic);
    }
    if (message.parent !== undefined) {
      writer.uint32(26).string(message.parent);
    }
    if (message.type !== GrpcStorageObjectType.FOLDER) {
      writer.uint32(32).int32(grpcStorageObjectTypeToNumber(message.type));
    }
    if (message.file !== undefined) {
      writer.uint32(42).string(message.file);
    }
    if (message.image !== undefined) {
      writer.uint32(50).string(message.image);
    }
    if (message.video !== undefined) {
      writer.uint32(58).string(message.video);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = grpcStorageObjectTypeFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.image = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.video = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectCreate {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : undefined,
      type: isSet(object.type) ? grpcStorageObjectTypeFromJSON(object.type) : GrpcStorageObjectType.FOLDER,
      file: isSet(object.file) ? globalThis.String(object.file) : undefined,
      image: isSet(object.image) ? globalThis.String(object.image) : undefined,
      video: isSet(object.video) ? globalThis.String(object.video) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectCreate): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.parent !== undefined) {
      obj.parent = message.parent;
    }
    if (message.type !== GrpcStorageObjectType.FOLDER) {
      obj.type = grpcStorageObjectTypeToJSON(message.type);
    }
    if (message.file !== undefined) {
      obj.file = message.file;
    }
    if (message.image !== undefined) {
      obj.image = message.image;
    }
    if (message.video !== undefined) {
      obj.video = message.video;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectCreate>, I>>(base?: I): GrpcStorageObjectCreate {
    return GrpcStorageObjectCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectCreate>, I>>(object: I): GrpcStorageObjectCreate {
    const message = createBaseGrpcStorageObjectCreate();
    message.name = object.name ?? "";
    message.isPublic = object.isPublic ?? false;
    message.parent = object.parent ?? undefined;
    message.type = object.type ?? GrpcStorageObjectType.FOLDER;
    message.file = object.file ?? undefined;
    message.image = object.image ?? undefined;
    message.video = object.video ?? undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectMetadata(): GrpcStorageObjectMetadata {
  return { name: "", isPublic: false, parent: "" };
}

export const GrpcStorageObjectMetadata: MessageFns<GrpcStorageObjectMetadata> = {
  encode(message: GrpcStorageObjectMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.isPublic !== false) {
      writer.uint32(16).bool(message.isPublic);
    }
    if (message.parent !== "") {
      writer.uint32(26).string(message.parent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectMetadata {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
    };
  },

  toJSON(message: GrpcStorageObjectMetadata): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectMetadata>, I>>(base?: I): GrpcStorageObjectMetadata {
    return GrpcStorageObjectMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectMetadata>, I>>(object: I): GrpcStorageObjectMetadata {
    const message = createBaseGrpcStorageObjectMetadata();
    message.name = object.name ?? "";
    message.isPublic = object.isPublic ?? false;
    message.parent = object.parent ?? "";
    return message;
  },
};

function createBaseGrpcStorageObjectManyMetadata(): GrpcStorageObjectManyMetadata {
  return { isPublic: false, parent: "" };
}

export const GrpcStorageObjectManyMetadata: MessageFns<GrpcStorageObjectManyMetadata> = {
  encode(message: GrpcStorageObjectManyMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isPublic !== false) {
      writer.uint32(8).bool(message.isPublic);
    }
    if (message.parent !== "") {
      writer.uint32(18).string(message.parent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectManyMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectManyMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectManyMetadata {
    return {
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
    };
  },

  toJSON(message: GrpcStorageObjectManyMetadata): unknown {
    const obj: any = {};
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectManyMetadata>, I>>(base?: I): GrpcStorageObjectManyMetadata {
    return GrpcStorageObjectManyMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectManyMetadata>, I>>(
    object: I,
  ): GrpcStorageObjectManyMetadata {
    const message = createBaseGrpcStorageObjectManyMetadata();
    message.isPublic = object.isPublic ?? false;
    message.parent = object.parent ?? "";
    return message;
  },
};

function createBaseGrpcStorageObjectUpdateSet(): GrpcStorageObjectUpdateSet {
  return { name: undefined, isPublic: undefined, parent: undefined };
}

export const GrpcStorageObjectUpdateSet: MessageFns<GrpcStorageObjectUpdateSet> = {
  encode(message: GrpcStorageObjectUpdateSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined) {
      writer.uint32(10).string(message.name);
    }
    if (message.isPublic !== undefined) {
      writer.uint32(16).bool(message.isPublic);
    }
    if (message.parent !== undefined) {
      writer.uint32(26).string(message.parent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectUpdateSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectUpdateSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectUpdateSet {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : undefined,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectUpdateSet): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.isPublic !== undefined) {
      obj.isPublic = message.isPublic;
    }
    if (message.parent !== undefined) {
      obj.parent = message.parent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectUpdateSet>, I>>(base?: I): GrpcStorageObjectUpdateSet {
    return GrpcStorageObjectUpdateSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectUpdateSet>, I>>(object: I): GrpcStorageObjectUpdateSet {
    const message = createBaseGrpcStorageObjectUpdateSet();
    message.name = object.name ?? undefined;
    message.isPublic = object.isPublic ?? undefined;
    message.parent = object.parent ?? undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectUpdate(): GrpcStorageObjectUpdate {
  return { set: undefined };
}

export const GrpcStorageObjectUpdate: MessageFns<GrpcStorageObjectUpdate> = {
  encode(message: GrpcStorageObjectUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.set !== undefined) {
      GrpcStorageObjectUpdateSet.encode(message.set, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.set = GrpcStorageObjectUpdateSet.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectUpdate {
    return { set: isSet(object.set) ? GrpcStorageObjectUpdateSet.fromJSON(object.set) : undefined };
  },

  toJSON(message: GrpcStorageObjectUpdate): unknown {
    const obj: any = {};
    if (message.set !== undefined) {
      obj.set = GrpcStorageObjectUpdateSet.toJSON(message.set);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectUpdate>, I>>(base?: I): GrpcStorageObjectUpdate {
    return GrpcStorageObjectUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectUpdate>, I>>(object: I): GrpcStorageObjectUpdate {
    const message = createBaseGrpcStorageObjectUpdate();
    message.set = (object.set !== undefined && object.set !== null)
      ? GrpcStorageObjectUpdateSet.fromPartial(object.set)
      : undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectUpdateRequest(): GrpcStorageObjectUpdateRequest {
  return { query: undefined, update: undefined };
}

export const GrpcStorageObjectUpdateRequest: MessageFns<GrpcStorageObjectUpdateRequest> = {
  encode(message: GrpcStorageObjectUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      GrpcBaseQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    if (message.update !== undefined) {
      GrpcStorageObjectUpdate.encode(message.update, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = GrpcBaseQuery.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.update = GrpcStorageObjectUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectUpdateRequest {
    return {
      query: isSet(object.query) ? GrpcBaseQuery.fromJSON(object.query) : undefined,
      update: isSet(object.update) ? GrpcStorageObjectUpdate.fromJSON(object.update) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectUpdateRequest): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = GrpcBaseQuery.toJSON(message.query);
    }
    if (message.update !== undefined) {
      obj.update = GrpcStorageObjectUpdate.toJSON(message.update);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectUpdateRequest>, I>>(base?: I): GrpcStorageObjectUpdateRequest {
    return GrpcStorageObjectUpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectUpdateRequest>, I>>(
    object: I,
  ): GrpcStorageObjectUpdateRequest {
    const message = createBaseGrpcStorageObjectUpdateRequest();
    message.query = (object.query !== undefined && object.query !== null)
      ? GrpcBaseQuery.fromPartial(object.query)
      : undefined;
    message.update = (object.update !== undefined && object.update !== null)
      ? GrpcStorageObjectUpdate.fromPartial(object.update)
      : undefined;
    return message;
  },
};

function createBaseGrpcStorageObjectUpdateByIdRequest(): GrpcStorageObjectUpdateByIdRequest {
  return { id: "", update: undefined };
}

export const GrpcStorageObjectUpdateByIdRequest: MessageFns<GrpcStorageObjectUpdateByIdRequest> = {
  encode(message: GrpcStorageObjectUpdateByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.update !== undefined) {
      GrpcStorageObjectUpdate.encode(message.update, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcStorageObjectUpdateByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcStorageObjectUpdateByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.update = GrpcStorageObjectUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcStorageObjectUpdateByIdRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      update: isSet(object.update) ? GrpcStorageObjectUpdate.fromJSON(object.update) : undefined,
    };
  },

  toJSON(message: GrpcStorageObjectUpdateByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.update !== undefined) {
      obj.update = GrpcStorageObjectUpdate.toJSON(message.update);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcStorageObjectUpdateByIdRequest>, I>>(
    base?: I,
  ): GrpcStorageObjectUpdateByIdRequest {
    return GrpcStorageObjectUpdateByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcStorageObjectUpdateByIdRequest>, I>>(
    object: I,
  ): GrpcStorageObjectUpdateByIdRequest {
    const message = createBaseGrpcStorageObjectUpdateByIdRequest();
    message.id = object.id ?? "";
    message.update = (object.update !== undefined && object.update !== null)
      ? GrpcStorageObjectUpdate.fromPartial(object.update)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): GrpcTimestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: GrpcTimestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(GrpcTimestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
