// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/messages/auth.messages.proto

/* eslint-disable */
import type { GrpcUser } from "../models/user";

export interface GrpcAuthLogin {
  login: string;
  password: string;
}

export interface GrpcAuthMe {
  accessToken: string;
}

export interface GrpcAuthRefresh {
  refreshToken: string;
}

export interface GrpcAuthToken {
  value: string;
  expireDate: Date;
}

export interface GrpcAuthTokens {
  accessToken: GrpcAuthToken;
  refreshToken: GrpcAuthToken;
}

export interface GrpcAuthData {
  user: GrpcUser;
  tokens: GrpcAuthTokens;
}

export interface GrpcAuthStreamCode {
  code: string;
  expireDate: Date;
}
