// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/messages/temp-code.messages.proto

/* eslint-disable */
import type { GrpcTempCode } from '../models/temp-code';

export interface GrpcTempCodeGetListResponse {
  items: GrpcTempCode[];
  total: number;
}

export interface GrpcTempCodeCreate {
  user: string;
}
