// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/temp-code/temp-code.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { TempCode } from './temp-code';

export interface TempCodeQuery {
  id?: string;
  ids: string[];
  user?: string;
}

export interface TempCodeList {
  items: TempCode[];
  total: number;
}

export interface TempCodeCreate {
  user: string;
}

function createBaseTempCodeQuery(): TempCodeQuery {
  return { id: undefined, ids: [], user: undefined };
}

export const TempCodeQuery: MessageFns<TempCodeQuery> = {
  encode(message: TempCodeQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    if (message.user !== undefined) {
      writer.uint32(26).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TempCodeQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTempCodeQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TempCodeQuery {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      ids: globalThis.Array.isArray(object?.ids)
        ? object.ids.map((e: any) => globalThis.String(e))
        : [],
      user: isSet(object.user) ? globalThis.String(object.user) : undefined,
    };
  },

  toJSON(message: TempCodeQuery): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    if (message.user !== undefined) {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TempCodeQuery>, I>>(base?: I): TempCodeQuery {
    return TempCodeQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TempCodeQuery>, I>>(object: I): TempCodeQuery {
    const message = createBaseTempCodeQuery();
    message.id = object.id ?? undefined;
    message.ids = object.ids?.map((e) => e) || [];
    message.user = object.user ?? undefined;
    return message;
  },
};

function createBaseTempCodeList(): TempCodeList {
  return { items: [], total: 0 };
}

export const TempCodeList: MessageFns<TempCodeList> = {
  encode(message: TempCodeList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      TempCode.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TempCodeList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTempCodeList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(TempCode.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TempCodeList {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => TempCode.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: TempCodeList): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => TempCode.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TempCodeList>, I>>(base?: I): TempCodeList {
    return TempCodeList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TempCodeList>, I>>(object: I): TempCodeList {
    const message = createBaseTempCodeList();
    message.items = object.items?.map((e) => TempCode.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseTempCodeCreate(): TempCodeCreate {
  return { user: '' };
}

export const TempCodeCreate: MessageFns<TempCodeCreate> = {
  encode(message: TempCodeCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== '') {
      writer.uint32(10).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TempCodeCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTempCodeCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TempCodeCreate {
    return { user: isSet(object.user) ? globalThis.String(object.user) : '' };
  },

  toJSON(message: TempCodeCreate): unknown {
    const obj: any = {};
    if (message.user !== '') {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TempCodeCreate>, I>>(base?: I): TempCodeCreate {
    return TempCodeCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TempCodeCreate>, I>>(object: I): TempCodeCreate {
    const message = createBaseTempCodeCreate();
    message.user = object.user ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
