// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/fields.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export interface IdField {
  id: string;
}

export interface IdsField {
  ids: string[];
}

export interface UserIdField {
  userId: string;
}

export interface UserField {
  user: string;
}

function createBaseIdField(): IdField {
  return { id: '' };
}

export const IdField: MessageFns<IdField> = {
  encode(message: IdField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdField {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: IdField): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdField>, I>>(base?: I): IdField {
    return IdField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdField>, I>>(object: I): IdField {
    const message = createBaseIdField();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseIdsField(): IdsField {
  return { ids: [] };
}

export const IdsField: MessageFns<IdsField> = {
  encode(message: IdsField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdsField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdsField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdsField {
    return {
      ids: globalThis.Array.isArray(object?.ids)
        ? object.ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: IdsField): unknown {
    const obj: any = {};
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdsField>, I>>(base?: I): IdsField {
    return IdsField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdsField>, I>>(object: I): IdsField {
    const message = createBaseIdsField();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseUserIdField(): UserIdField {
  return { userId: '' };
}

export const UserIdField: MessageFns<UserIdField> = {
  encode(message: UserIdField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserIdField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserIdField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserIdField {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : '' };
  },

  toJSON(message: UserIdField): unknown {
    const obj: any = {};
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserIdField>, I>>(base?: I): UserIdField {
    return UserIdField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserIdField>, I>>(object: I): UserIdField {
    const message = createBaseUserIdField();
    message.userId = object.userId ?? '';
    return message;
  },
};

function createBaseUserField(): UserField {
  return { user: '' };
}

export const UserField: MessageFns<UserField> = {
  encode(message: UserField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== '') {
      writer.uint32(10).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserField {
    return { user: isSet(object.user) ? globalThis.String(object.user) : '' };
  },

  toJSON(message: UserField): unknown {
    const obj: any = {};
    if (message.user !== '') {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserField>, I>>(base?: I): UserField {
    return UserField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserField>, I>>(object: I): UserField {
    const message = createBaseUserField();
    message.user = object.user ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
