// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../google/protobuf/timestamp';
import { CrudConditionalFilter, CrudLogicalFilter, CrudSorter } from './crud';

export interface IdField {
  id: string;
}

export interface IdsField {
  ids: string[];
}

export interface EntityWithTimestamps {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
}

export interface BaseQuery {
  id?: string;
  ids: string[];
}

export interface BaseRequest {
  query: BaseQuery;
}

export interface Pagination {
  page?: number;
  limit?: number;
}

export interface GetListRequest {
  logicalFilters: CrudLogicalFilter[];
  conditionalFilters: CrudConditionalFilter[];
  sorters: CrudSorter[];
  pagination?: Pagination;
}

export interface BooleanResult {
  value: boolean;
}

function createBaseIdField(): IdField {
  return { id: '' };
}

export const IdField: MessageFns<IdField> = {
  encode(message: IdField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdField {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: IdField): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdField>, I>>(base?: I): IdField {
    return IdField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdField>, I>>(object: I): IdField {
    const message = createBaseIdField();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseIdsField(): IdsField {
  return { ids: [] };
}

export const IdsField: MessageFns<IdsField> = {
  encode(message: IdsField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdsField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdsField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdsField {
    return {
      ids: globalThis.Array.isArray(object?.ids)
        ? object.ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: IdsField): unknown {
    const obj: any = {};
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdsField>, I>>(base?: I): IdsField {
    return IdsField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdsField>, I>>(object: I): IdsField {
    const message = createBaseIdsField();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseEntityWithTimestamps(): EntityWithTimestamps {
  return { id: '', createdAt: undefined, updatedAt: undefined };
}

export const EntityWithTimestamps: MessageFns<EntityWithTimestamps> = {
  encode(message: EntityWithTimestamps, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(18).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityWithTimestamps {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityWithTimestamps();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EntityWithTimestamps {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: EntityWithTimestamps): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EntityWithTimestamps>, I>>(base?: I): EntityWithTimestamps {
    return EntityWithTimestamps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityWithTimestamps>, I>>(
    object: I,
  ): EntityWithTimestamps {
    const message = createBaseEntityWithTimestamps();
    message.id = object.id ?? '';
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseBaseQuery(): BaseQuery {
  return { id: undefined, ids: [] };
}

export const BaseQuery: MessageFns<BaseQuery> = {
  encode(message: BaseQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseQuery {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      ids: globalThis.Array.isArray(object?.ids)
        ? object.ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: BaseQuery): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BaseQuery>, I>>(base?: I): BaseQuery {
    return BaseQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BaseQuery>, I>>(object: I): BaseQuery {
    const message = createBaseBaseQuery();
    message.id = object.id ?? undefined;
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseBaseRequest(): BaseRequest {
  return { query: undefined };
}

export const BaseRequest: MessageFns<BaseRequest> = {
  encode(message: BaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      BaseQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = BaseQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseRequest {
    return { query: isSet(object.query) ? BaseQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: BaseRequest): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = BaseQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BaseRequest>, I>>(base?: I): BaseRequest {
    return BaseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BaseRequest>, I>>(object: I): BaseRequest {
    const message = createBaseBaseRequest();
    message.query =
      object.query !== undefined && object.query !== null
        ? BaseQuery.fromPartial(object.query)
        : undefined;
    return message;
  },
};

function createBasePagination(): Pagination {
  return { page: undefined, limit: undefined };
}

export const Pagination: MessageFns<Pagination> = {
  encode(message: Pagination, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== undefined) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pagination {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePagination();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Pagination {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : undefined,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
    };
  },

  toJSON(message: Pagination): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== undefined) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Pagination>, I>>(base?: I): Pagination {
    return Pagination.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pagination>, I>>(object: I): Pagination {
    const message = createBasePagination();
    message.page = object.page ?? undefined;
    message.limit = object.limit ?? undefined;
    return message;
  },
};

function createBaseGetListRequest(): GetListRequest {
  return { logicalFilters: [], conditionalFilters: [], sorters: [], pagination: undefined };
}

export const GetListRequest: MessageFns<GetListRequest> = {
  encode(message: GetListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.logicalFilters) {
      CrudLogicalFilter.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.conditionalFilters) {
      CrudConditionalFilter.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.sorters) {
      CrudSorter.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.pagination !== undefined) {
      Pagination.encode(message.pagination, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logicalFilters.push(CrudLogicalFilter.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.conditionalFilters.push(CrudConditionalFilter.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sorters.push(CrudSorter.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pagination = Pagination.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetListRequest {
    return {
      logicalFilters: globalThis.Array.isArray(object?.logicalFilters)
        ? object.logicalFilters.map((e: any) => CrudLogicalFilter.fromJSON(e))
        : [],
      conditionalFilters: globalThis.Array.isArray(object?.conditionalFilters)
        ? object.conditionalFilters.map((e: any) => CrudConditionalFilter.fromJSON(e))
        : [],
      sorters: globalThis.Array.isArray(object?.sorters)
        ? object.sorters.map((e: any) => CrudSorter.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? Pagination.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: GetListRequest): unknown {
    const obj: any = {};
    if (message.logicalFilters?.length) {
      obj.logicalFilters = message.logicalFilters.map((e) => CrudLogicalFilter.toJSON(e));
    }
    if (message.conditionalFilters?.length) {
      obj.conditionalFilters = message.conditionalFilters.map((e) =>
        CrudConditionalFilter.toJSON(e),
      );
    }
    if (message.sorters?.length) {
      obj.sorters = message.sorters.map((e) => CrudSorter.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = Pagination.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetListRequest>, I>>(base?: I): GetListRequest {
    return GetListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetListRequest>, I>>(object: I): GetListRequest {
    const message = createBaseGetListRequest();
    message.logicalFilters =
      object.logicalFilters?.map((e) => CrudLogicalFilter.fromPartial(e)) || [];
    message.conditionalFilters =
      object.conditionalFilters?.map((e) => CrudConditionalFilter.fromPartial(e)) || [];
    message.sorters = object.sorters?.map((e) => CrudSorter.fromPartial(e)) || [];
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? Pagination.fromPartial(object.pagination)
        : undefined;
    return message;
  },
};

function createBaseBooleanResult(): BooleanResult {
  return { value: false };
}

export const BooleanResult: MessageFns<BooleanResult> = {
  encode(message: BooleanResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== false) {
      writer.uint32(8).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BooleanResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooleanResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BooleanResult {
    return { value: isSet(object.value) ? globalThis.Boolean(object.value) : false };
  },

  toJSON(message: BooleanResult): unknown {
    const obj: any = {};
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BooleanResult>, I>>(base?: I): BooleanResult {
    return BooleanResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BooleanResult>, I>>(object: I): BooleanResult {
    const message = createBaseBooleanResult();
    message.value = object.value ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
