// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/messages/common.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface DownloadData {
  url: string;
  fileName: string;
}

export interface UrlMap {
  items: Map<string, string>;
}

export interface UrlMap_ItemsEntry {
  key: string;
  value: string;
}

export interface DownloadMap {
  items: Map<string, DownloadData>;
}

export interface DownloadMap_ItemsEntry {
  key: string;
  value: DownloadData;
}

export interface UploadRequest {
  id?: string;
  chunk?: Uint8Array<ArrayBufferLike>;
}

function createBaseDownloadData(): DownloadData {
  return { url: "", fileName: "" };
}

export const DownloadData: MessageFns<DownloadData> = {
  encode(message: DownloadData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownloadData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadData {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      fileName: isSet(object.fileName) ? globalThis.String(object.fileName) : "",
    };
  },

  toJSON(message: DownloadData): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.fileName !== "") {
      obj.fileName = message.fileName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadData>, I>>(base?: I): DownloadData {
    return DownloadData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadData>, I>>(object: I): DownloadData {
    const message = createBaseDownloadData();
    message.url = object.url ?? "";
    message.fileName = object.fileName ?? "";
    return message;
  },
};

function createBaseUrlMap(): UrlMap {
  return { items: new Map() };
}

export const UrlMap: MessageFns<UrlMap> = {
  encode(message: UrlMap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    message.items.forEach((value, key) => {
      UrlMap_ItemsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UrlMap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUrlMap();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = UrlMap_ItemsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.items.set(entry1.key, entry1.value);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UrlMap {
    return {
      items: isObject(object.items)
        ? (globalThis.Object.entries(object.items) as [string, any][]).reduce(
          (acc: Map<string, string>, [key, value]: [string, any]) => {
            acc.set(key, globalThis.String(value));
            return acc;
          },
          new Map(),
        )
        : new Map(),
    };
  },

  toJSON(message: UrlMap): unknown {
    const obj: any = {};
    if (message.items?.size) {
      obj.items = {};
      message.items.forEach((v, k) => {
        obj.items[k] = v;
      });
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UrlMap>, I>>(base?: I): UrlMap {
    return UrlMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UrlMap>, I>>(object: I): UrlMap {
    const message = createBaseUrlMap();
    message.items = (() => {
      const m = new Map();
      (object.items as Map<string, string> ?? new Map()).forEach((value, key) => {
        if (value !== undefined) {
          m.set(key, globalThis.String(value));
        }
      });
      return m;
    })();
    return message;
  },
};

function createBaseUrlMap_ItemsEntry(): UrlMap_ItemsEntry {
  return { key: "", value: "" };
}

export const UrlMap_ItemsEntry: MessageFns<UrlMap_ItemsEntry> = {
  encode(message: UrlMap_ItemsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UrlMap_ItemsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUrlMap_ItemsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UrlMap_ItemsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: UrlMap_ItemsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UrlMap_ItemsEntry>, I>>(base?: I): UrlMap_ItemsEntry {
    return UrlMap_ItemsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UrlMap_ItemsEntry>, I>>(object: I): UrlMap_ItemsEntry {
    const message = createBaseUrlMap_ItemsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDownloadMap(): DownloadMap {
  return { items: new Map() };
}

export const DownloadMap: MessageFns<DownloadMap> = {
  encode(message: DownloadMap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    message.items.forEach((value, key) => {
      DownloadMap_ItemsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownloadMap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadMap();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = DownloadMap_ItemsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.items.set(entry1.key, entry1.value);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadMap {
    return {
      items: isObject(object.items)
        ? (globalThis.Object.entries(object.items) as [string, any][]).reduce(
          (acc: Map<string, DownloadData>, [key, value]: [string, any]) => {
            acc.set(key, DownloadData.fromJSON(value));
            return acc;
          },
          new Map(),
        )
        : new Map(),
    };
  },

  toJSON(message: DownloadMap): unknown {
    const obj: any = {};
    if (message.items?.size) {
      obj.items = {};
      message.items.forEach((v, k) => {
        obj.items[k] = DownloadData.toJSON(v);
      });
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadMap>, I>>(base?: I): DownloadMap {
    return DownloadMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadMap>, I>>(object: I): DownloadMap {
    const message = createBaseDownloadMap();
    message.items = (() => {
      const m = new Map();
      (object.items as Map<string, DownloadData> ?? new Map()).forEach((value, key) => {
        if (value !== undefined) {
          m.set(key, DownloadData.fromPartial(value));
        }
      });
      return m;
    })();
    return message;
  },
};

function createBaseDownloadMap_ItemsEntry(): DownloadMap_ItemsEntry {
  return { key: "", value: undefined };
}

export const DownloadMap_ItemsEntry: MessageFns<DownloadMap_ItemsEntry> = {
  encode(message: DownloadMap_ItemsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      DownloadData.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownloadMap_ItemsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadMap_ItemsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = DownloadData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadMap_ItemsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? DownloadData.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DownloadMap_ItemsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = DownloadData.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadMap_ItemsEntry>, I>>(base?: I): DownloadMap_ItemsEntry {
    return DownloadMap_ItemsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadMap_ItemsEntry>, I>>(object: I): DownloadMap_ItemsEntry {
    const message = createBaseDownloadMap_ItemsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? DownloadData.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseUploadRequest(): UploadRequest {
  return { id: undefined, chunk: undefined };
}

export const UploadRequest: MessageFns<UploadRequest> = {
  encode(message: UploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.chunk !== undefined) {
      writer.uint32(18).bytes(message.chunk);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chunk = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      chunk: isSet(object.chunk) ? bytesFromBase64(object.chunk) : undefined,
    };
  },

  toJSON(message: UploadRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.chunk !== undefined) {
      obj.chunk = base64FromBytes(message.chunk);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadRequest>, I>>(base?: I): UploadRequest {
    return UploadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadRequest>, I>>(object: I): UploadRequest {
    const message = createBaseUploadRequest();
    message.id = object.id ?? undefined;
    message.chunk = object.chunk ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
