// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/file/file.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../../google/protobuf/timestamp';

export enum FileUploadStatus {
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  READY = 'READY',
}

export function fileUploadStatusFromJSON(object: any): FileUploadStatus {
  switch (object) {
    case 0:
    case 'PENDING':
      return FileUploadStatus.PENDING;
    case 1:
    case 'FAILED':
      return FileUploadStatus.FAILED;
    case 2:
    case 'READY':
      return FileUploadStatus.READY;
    default:
      throw new globalThis.Error(
        'Unrecognized enum value ' + object + ' for enum FileUploadStatus',
      );
  }
}

export function fileUploadStatusToJSON(object: FileUploadStatus): string {
  switch (object) {
    case FileUploadStatus.PENDING:
      return 'PENDING';
    case FileUploadStatus.FAILED:
      return 'FAILED';
    case FileUploadStatus.READY:
      return 'READY';
    default:
      throw new globalThis.Error(
        'Unrecognized enum value ' + object + ' for enum FileUploadStatus',
      );
  }
}

export function fileUploadStatusToNumber(object: FileUploadStatus): number {
  switch (object) {
    case FileUploadStatus.PENDING:
      return 0;
    case FileUploadStatus.FAILED:
      return 1;
    case FileUploadStatus.READY:
      return 2;
    default:
      throw new globalThis.Error(
        'Unrecognized enum value ' + object + ' for enum FileUploadStatus',
      );
  }
}

export interface File {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  originalName: string;
  size: number;
  mimeType: string;
  extension: string;
  uploadStatus: FileUploadStatus;
  providerId?: string;
  userId: string;
  uploadId: string;
}

function createBaseFile(): File {
  return {
    id: '',
    createdAt: undefined,
    updatedAt: undefined,
    originalName: '',
    size: 0,
    mimeType: '',
    extension: '',
    uploadStatus: FileUploadStatus.PENDING,
    providerId: undefined,
    userId: '',
    uploadId: '',
  };
}

export const File: MessageFns<File> = {
  encode(message: File, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(18).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).join();
    }
    if (message.originalName !== '') {
      writer.uint32(34).string(message.originalName);
    }
    if (message.size !== 0) {
      writer.uint32(40).int32(message.size);
    }
    if (message.mimeType !== '') {
      writer.uint32(50).string(message.mimeType);
    }
    if (message.extension !== '') {
      writer.uint32(58).string(message.extension);
    }
    if (message.uploadStatus !== FileUploadStatus.PENDING) {
      writer.uint32(64).int32(fileUploadStatusToNumber(message.uploadStatus));
    }
    if (message.providerId !== undefined) {
      writer.uint32(74).string(message.providerId);
    }
    if (message.userId !== '') {
      writer.uint32(82).string(message.userId);
    }
    if (message.uploadId !== '') {
      writer.uint32(90).string(message.uploadId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): File {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originalName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.extension = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.uploadStatus = fileUploadStatusFromJSON(reader.int32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.providerId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.uploadId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
      originalName: isSet(object.originalName) ? globalThis.String(object.originalName) : '',
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      mimeType: isSet(object.mimeType) ? globalThis.String(object.mimeType) : '',
      extension: isSet(object.extension) ? globalThis.String(object.extension) : '',
      uploadStatus: isSet(object.uploadStatus)
        ? fileUploadStatusFromJSON(object.uploadStatus)
        : FileUploadStatus.PENDING,
      providerId: isSet(object.providerId) ? globalThis.String(object.providerId) : undefined,
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      uploadId: isSet(object.uploadId) ? globalThis.String(object.uploadId) : '',
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.originalName !== '') {
      obj.originalName = message.originalName;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.mimeType !== '') {
      obj.mimeType = message.mimeType;
    }
    if (message.extension !== '') {
      obj.extension = message.extension;
    }
    if (message.uploadStatus !== FileUploadStatus.PENDING) {
      obj.uploadStatus = fileUploadStatusToJSON(message.uploadStatus);
    }
    if (message.providerId !== undefined) {
      obj.providerId = message.providerId;
    }
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.uploadId !== '') {
      obj.uploadId = message.uploadId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<File>, I>>(base?: I): File {
    return File.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<File>, I>>(object: I): File {
    const message = createBaseFile();
    message.id = object.id ?? '';
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.originalName = object.originalName ?? '';
    message.size = object.size ?? 0;
    message.mimeType = object.mimeType ?? '';
    message.extension = object.extension ?? '';
    message.uploadStatus = object.uploadStatus ?? FileUploadStatus.PENDING;
    message.providerId = object.providerId ?? undefined;
    message.userId = object.userId ?? '';
    message.uploadId = object.uploadId ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
