// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/temp-code.service.proto

/* eslint-disable */
import { type Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import {
  type GrpcProxyControllerFactory,
  type GrpcProxyControllerFactoryParams,
  type GrpcProxyControllerFactoryResult,
  type GrpcProxyMethodParams,
} from '../__compiler__';
import { type GrpcGetListRequest, type GrpcIdField } from '../common/service';
import {
  type GrpcTempCodeCreate,
  GrpcTempCodeGetListResponse,
} from './messages/temp-code.messages';
import { GrpcTempCode } from './models/temp-code';

export interface GrpcTempCodeServiceClient {
  getById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcTempCode>;

  getList(
    request: GrpcGetListRequest,
    metadata?: Metadata,
  ): Observable<GrpcTempCodeGetListResponse>;

  createOne(request: GrpcTempCodeCreate, metadata?: Metadata): Observable<GrpcTempCode>;

  deleteById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcTempCode>;
}

export interface GrpcTempCodeServiceController {
  getById(
    request: GrpcIdField,
    metadata?: Metadata,
  ): Promise<GrpcTempCode> | Observable<GrpcTempCode> | GrpcTempCode;

  getList(
    request: GrpcGetListRequest,
    metadata?: Metadata,
  ):
    | Promise<GrpcTempCodeGetListResponse>
    | Observable<GrpcTempCodeGetListResponse>
    | GrpcTempCodeGetListResponse;

  createOne(
    request: GrpcTempCodeCreate,
    metadata?: Metadata,
  ): Promise<GrpcTempCode> | Observable<GrpcTempCode> | GrpcTempCode;

  deleteById(
    request: GrpcIdField,
    metadata?: Metadata,
  ): Promise<GrpcTempCode> | Observable<GrpcTempCode> | GrpcTempCode;
}

function TempCodeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getById', 'getList', 'createOne', 'deleteById'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('TempCodeService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('TempCodeService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

const TEMP_CODE_SERVICE_NAME = 'TempCodeService';

interface GrpcTempCodeProxyMethodParams {
  getById?: GrpcProxyMethodParams<GrpcIdField>;
  getList?: GrpcProxyMethodParams<GrpcGetListRequest>;
  createOne?: GrpcProxyMethodParams<GrpcTempCodeCreate>;
  deleteById?: GrpcProxyMethodParams<GrpcIdField>;
}

export const GrpcTempCodeService = {
  name: 'TempCodeService',
  definition: {
    package: 'auth',
    protoPath: 'auth/temp-code.service.proto',
  },
  proxyFactory: (methodParams: GrpcTempCodeProxyMethodParams = {}): GrpcProxyControllerFactory => {
    return (
      controllerParams: GrpcProxyControllerFactoryParams,
    ): GrpcProxyControllerFactoryResult => {
      const { GrpcController, GrpcMethod, InjectGrpcService, proxyPipes } = controllerParams;

      @GrpcController()
      @TempCodeServiceControllerMethods()
      class GrpcTempCodeProxyController {
        constructor(
          @InjectGrpcService(TEMP_CODE_SERVICE_NAME)
          private readonly client: GrpcTempCodeServiceClient,
        ) {}

        @GrpcMethod(methodParams.getById)
        getById(
          request: GrpcIdField,
          metadata?: Metadata,
        ): GrpcTempCode | Promise<GrpcTempCode> | Observable<GrpcTempCode> {
          //@ts-ignore
          return this.client.getById(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getList)
        getList(
          request: GrpcGetListRequest,
          metadata?: Metadata,
        ):
          | GrpcTempCodeGetListResponse
          | Promise<GrpcTempCodeGetListResponse>
          | Observable<GrpcTempCodeGetListResponse> {
          //@ts-ignore
          return this.client.getList(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.createOne)
        createOne(
          request: GrpcTempCodeCreate,
          metadata?: Metadata,
        ): GrpcTempCode | Promise<GrpcTempCode> | Observable<GrpcTempCode> {
          //@ts-ignore
          return this.client.createOne(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.deleteById)
        deleteById(
          request: GrpcIdField,
          metadata?: Metadata,
        ): GrpcTempCode | Promise<GrpcTempCode> | Observable<GrpcTempCode> {
          //@ts-ignore
          return this.client.deleteById(request, metadata?.clone()).pipe(...proxyPipes);
        }
      }

      return {
        Controller: GrpcTempCodeProxyController,
        service: 'TempCodeService',
      };
    };
  },
  ControllerMethods: (): ClassDecorator => TempCodeServiceControllerMethods(),
} as const;
