// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/user.service.proto

/* eslint-disable */
import { type Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import {
  type GrpcProxyControllerFactory,
  type GrpcProxyControllerFactoryParams,
  type GrpcProxyControllerFactoryResult,
  type GrpcProxyMethodParams,
} from '../__compiler__';
import { type GrpcGetListRequest, type GrpcIdField } from '../common/service';
import {
  type GrpcUserCreate,
  GrpcUserGetListResponse,
  GrpcUserList,
  type GrpcUserRequest,
  type GrpcUserUpdateByIdRequest,
} from './messages/user.messages';
import { GrpcUser } from './models/user';

export interface GrpcUserServiceClient {
  getById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcUser>;

  getOne(request: GrpcUserRequest, metadata?: Metadata): Observable<GrpcUser>;

  getMany(request: GrpcUserRequest, metadata?: Metadata): Observable<GrpcUserList>;

  getList(request: GrpcGetListRequest, metadata?: Metadata): Observable<GrpcUserGetListResponse>;

  createOne(request: GrpcUserCreate, metadata?: Metadata): Observable<GrpcUser>;

  updateById(request: GrpcUserUpdateByIdRequest, metadata?: Metadata): Observable<GrpcUser>;

  deleteById(request: GrpcIdField, metadata?: Metadata): Observable<GrpcUser>;
}

export interface GrpcUserServiceController {
  getById(
    request: GrpcIdField,
    metadata?: Metadata,
  ): Promise<GrpcUser> | Observable<GrpcUser> | GrpcUser;

  getOne(
    request: GrpcUserRequest,
    metadata?: Metadata,
  ): Promise<GrpcUser> | Observable<GrpcUser> | GrpcUser;

  getMany(
    request: GrpcUserRequest,
    metadata?: Metadata,
  ): Promise<GrpcUserList> | Observable<GrpcUserList> | GrpcUserList;

  getList(
    request: GrpcGetListRequest,
    metadata?: Metadata,
  ):
    | Promise<GrpcUserGetListResponse>
    | Observable<GrpcUserGetListResponse>
    | GrpcUserGetListResponse;

  createOne(
    request: GrpcUserCreate,
    metadata?: Metadata,
  ): Promise<GrpcUser> | Observable<GrpcUser> | GrpcUser;

  updateById(
    request: GrpcUserUpdateByIdRequest,
    metadata?: Metadata,
  ): Promise<GrpcUser> | Observable<GrpcUser> | GrpcUser;

  deleteById(
    request: GrpcIdField,
    metadata?: Metadata,
  ): Promise<GrpcUser> | Observable<GrpcUser> | GrpcUser;
}

function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getById',
      'getOne',
      'getMany',
      'getList',
      'createOne',
      'updateById',
      'deleteById',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('UserService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('UserService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

const USER_SERVICE_NAME = 'UserService';

interface GrpcUserProxyMethodParams {
  getById?: GrpcProxyMethodParams<GrpcIdField>;
  getOne?: GrpcProxyMethodParams<GrpcUserRequest>;
  getMany?: GrpcProxyMethodParams<GrpcUserRequest>;
  getList?: GrpcProxyMethodParams<GrpcGetListRequest>;
  createOne?: GrpcProxyMethodParams<GrpcUserCreate>;
  updateById?: GrpcProxyMethodParams<GrpcUserUpdateByIdRequest>;
  deleteById?: GrpcProxyMethodParams<GrpcIdField>;
}

export const GrpcUserService = {
  name: 'UserService',
  definition: {
    package: 'auth',
    protoPath: 'auth/user.service.proto',
  },
  proxyFactory: (methodParams: GrpcUserProxyMethodParams = {}): GrpcProxyControllerFactory => {
    return (
      controllerParams: GrpcProxyControllerFactoryParams,
    ): GrpcProxyControllerFactoryResult => {
      const { GrpcController, GrpcMethod, InjectGrpcService, proxyPipes } = controllerParams;

      @GrpcController()
      @UserServiceControllerMethods()
      class GrpcUserProxyController {
        constructor(
          @InjectGrpcService(USER_SERVICE_NAME)
          private readonly client: GrpcUserServiceClient,
        ) {}

        @GrpcMethod(methodParams.getById)
        getById(
          request: GrpcIdField,
          metadata?: Metadata,
        ): GrpcUser | Promise<GrpcUser> | Observable<GrpcUser> {
          //@ts-ignore
          return this.client.getById(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getOne)
        getOne(
          request: GrpcUserRequest,
          metadata?: Metadata,
        ): GrpcUser | Promise<GrpcUser> | Observable<GrpcUser> {
          //@ts-ignore
          return this.client.getOne(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getMany)
        getMany(
          request: GrpcUserRequest,
          metadata?: Metadata,
        ): GrpcUserList | Promise<GrpcUserList> | Observable<GrpcUserList> {
          //@ts-ignore
          return this.client.getMany(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.getList)
        getList(
          request: GrpcGetListRequest,
          metadata?: Metadata,
        ):
          | GrpcUserGetListResponse
          | Promise<GrpcUserGetListResponse>
          | Observable<GrpcUserGetListResponse> {
          //@ts-ignore
          return this.client.getList(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.createOne)
        createOne(
          request: GrpcUserCreate,
          metadata?: Metadata,
        ): GrpcUser | Promise<GrpcUser> | Observable<GrpcUser> {
          //@ts-ignore
          return this.client.createOne(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.updateById)
        updateById(
          request: GrpcUserUpdateByIdRequest,
          metadata?: Metadata,
        ): GrpcUser | Promise<GrpcUser> | Observable<GrpcUser> {
          //@ts-ignore
          return this.client.updateById(request, metadata?.clone()).pipe(...proxyPipes);
        }

        @GrpcMethod(methodParams.deleteById)
        deleteById(
          request: GrpcIdField,
          metadata?: Metadata,
        ): GrpcUser | Promise<GrpcUser> | Observable<GrpcUser> {
          //@ts-ignore
          return this.client.deleteById(request, metadata?.clone()).pipe(...proxyPipes);
        }
      }

      return {
        Controller: GrpcUserProxyController,
        service: 'UserService',
      };
    };
  },
  ControllerMethods: (): ClassDecorator => UserServiceControllerMethods(),
} as const;
