// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/messages/auth.messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { GrpcUser } from '../models/user';

export interface GrpcAuthLogin {
  login: string;
  password: string;
}

export interface GrpcAuthMe {
  accessToken: string;
}

export interface GrpcAuthRefresh {
  refreshToken: string;
}

export interface GrpcAuthToken {
  value: string;
  expireDate: Date;
}

export interface GrpcAuthTokens {
  accessToken: GrpcAuthToken;
  refreshToken: GrpcAuthToken;
}

export interface GrpcAuthData {
  user: GrpcUser;
  tokens: GrpcAuthTokens;
}

export interface GrpcAuthStreamCode {
  code: string;
  expireDate: Date;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
