// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/auth/auth.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../../google/protobuf/timestamp';
import { User } from '../user/user';

export interface AuthLogin {
  login: string;
  password: string;
}

export interface AuthRefresh {
  refreshToken: string;
}

export interface AuthToken {
  value: string;
  expiredAt: Date;
}

export interface AuthTokens {
  accessToken: AuthToken;
  refreshToken: AuthToken;
}

export interface AuthData {
  user: User;
  tokens: AuthTokens;
}

function createBaseAuthLogin(): AuthLogin {
  return { login: '', password: '' };
}

export const AuthLogin: MessageFns<AuthLogin> = {
  encode(message: AuthLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.login !== '') {
      writer.uint32(10).string(message.login);
    }
    if (message.password !== '') {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.login = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthLogin {
    return {
      login: isSet(object.login) ? globalThis.String(object.login) : '',
      password: isSet(object.password) ? globalThis.String(object.password) : '',
    };
  },

  toJSON(message: AuthLogin): unknown {
    const obj: any = {};
    if (message.login !== '') {
      obj.login = message.login;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthLogin>, I>>(base?: I): AuthLogin {
    return AuthLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthLogin>, I>>(object: I): AuthLogin {
    const message = createBaseAuthLogin();
    message.login = object.login ?? '';
    message.password = object.password ?? '';
    return message;
  },
};

function createBaseAuthRefresh(): AuthRefresh {
  return { refreshToken: '' };
}

export const AuthRefresh: MessageFns<AuthRefresh> = {
  encode(message: AuthRefresh, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== '') {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthRefresh {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthRefresh();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthRefresh {
    return {
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : '',
    };
  },

  toJSON(message: AuthRefresh): unknown {
    const obj: any = {};
    if (message.refreshToken !== '') {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthRefresh>, I>>(base?: I): AuthRefresh {
    return AuthRefresh.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthRefresh>, I>>(object: I): AuthRefresh {
    const message = createBaseAuthRefresh();
    message.refreshToken = object.refreshToken ?? '';
    return message;
  },
};

function createBaseAuthToken(): AuthToken {
  return { value: '', expiredAt: undefined };
}

export const AuthToken: MessageFns<AuthToken> = {
  encode(message: AuthToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== '') {
      writer.uint32(10).string(message.value);
    }
    if (message.expiredAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiredAt), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expiredAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthToken {
    return {
      value: isSet(object.value) ? globalThis.String(object.value) : '',
      expiredAt: isSet(object.expiredAt) ? fromJsonTimestamp(object.expiredAt) : undefined,
    };
  },

  toJSON(message: AuthToken): unknown {
    const obj: any = {};
    if (message.value !== '') {
      obj.value = message.value;
    }
    if (message.expiredAt !== undefined) {
      obj.expiredAt = message.expiredAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthToken>, I>>(base?: I): AuthToken {
    return AuthToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthToken>, I>>(object: I): AuthToken {
    const message = createBaseAuthToken();
    message.value = object.value ?? '';
    message.expiredAt = object.expiredAt ?? undefined;
    return message;
  },
};

function createBaseAuthTokens(): AuthTokens {
  return { accessToken: undefined, refreshToken: undefined };
}

export const AuthTokens: MessageFns<AuthTokens> = {
  encode(message: AuthTokens, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== undefined) {
      AuthToken.encode(message.accessToken, writer.uint32(10).fork()).join();
    }
    if (message.refreshToken !== undefined) {
      AuthToken.encode(message.refreshToken, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthTokens {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthTokens();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = AuthToken.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = AuthToken.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthTokens {
    return {
      accessToken: isSet(object.accessToken) ? AuthToken.fromJSON(object.accessToken) : undefined,
      refreshToken: isSet(object.refreshToken)
        ? AuthToken.fromJSON(object.refreshToken)
        : undefined,
    };
  },

  toJSON(message: AuthTokens): unknown {
    const obj: any = {};
    if (message.accessToken !== undefined) {
      obj.accessToken = AuthToken.toJSON(message.accessToken);
    }
    if (message.refreshToken !== undefined) {
      obj.refreshToken = AuthToken.toJSON(message.refreshToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthTokens>, I>>(base?: I): AuthTokens {
    return AuthTokens.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthTokens>, I>>(object: I): AuthTokens {
    const message = createBaseAuthTokens();
    message.accessToken =
      object.accessToken !== undefined && object.accessToken !== null
        ? AuthToken.fromPartial(object.accessToken)
        : undefined;
    message.refreshToken =
      object.refreshToken !== undefined && object.refreshToken !== null
        ? AuthToken.fromPartial(object.refreshToken)
        : undefined;
    return message;
  },
};

function createBaseAuthData(): AuthData {
  return { user: undefined, tokens: undefined };
}

export const AuthData: MessageFns<AuthData> = {
  encode(message: AuthData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.tokens !== undefined) {
      AuthTokens.encode(message.tokens, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokens = AuthTokens.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthData {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      tokens: isSet(object.tokens) ? AuthTokens.fromJSON(object.tokens) : undefined,
    };
  },

  toJSON(message: AuthData): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.tokens !== undefined) {
      obj.tokens = AuthTokens.toJSON(message.tokens);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthData>, I>>(base?: I): AuthData {
    return AuthData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthData>, I>>(object: I): AuthData {
    const message = createBaseAuthData();
    message.user =
      object.user !== undefined && object.user !== null ? User.fromPartial(object.user) : undefined;
    message.tokens =
      object.tokens !== undefined && object.tokens !== null
        ? AuthTokens.fromPartial(object.tokens)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
