// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: cv/contact.service.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { join } from "path";
import { Observable } from "rxjs";
import { GrpcProxyControllerFactory, GrpcProxyControllerFactoryParams, GrpcProxyControllerFactoryResult, GrpcProxyMethodParams, PROTO_PATH } from "../__compiler__";
import { GrpcContactList, GrpcContactRequest } from "./messages/contact.messages";

const CV_PACKAGE_NAME = "cv";

export interface GrpcContactServiceClient {
  getMany(request: GrpcContactRequest, metadata?: Metadata): Observable<GrpcContactList>;
}

export interface GrpcContactServiceController {
  getMany(
    request: GrpcContactRequest,
    metadata?: Metadata,
  ): Promise<GrpcContactList> | Observable<GrpcContactList> | GrpcContactList;
}

function ContactServiceControllerMethods() {
  return function(constructor: Function) {
    const grpcMethods: string[] = ["getMany"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ContactService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ContactService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

const CONTACT_SERVICE_NAME = "ContactService";

interface GrpcContactProxyMethodParams {
  getMany?: GrpcProxyMethodParams<GrpcContactRequest>;
}

export const GrpcContactService = {
  name: "ContactService",
  definition: {
    package: "cv",
    protoPath: join(PROTO_PATH, 'cv/contact.service.proto'),
  },
  proxyFactory: (methodParams: GrpcContactProxyMethodParams = {}): GrpcProxyControllerFactory => {
    return (controllerParams: GrpcProxyControllerFactoryParams): GrpcProxyControllerFactoryResult => {
      const { GrpcController, GrpcMethod, GrpcStreamMethod, InjectGrpcService, proxyPipes } = controllerParams;

      @GrpcController()
      @ContactServiceControllerMethods()
      class GrpcContactProxyController {
        constructor(
          @InjectGrpcService(CONTACT_SERVICE_NAME)
          private readonly client: GrpcContactServiceClient,
        ) { }

        @GrpcMethod(methodParams.getMany)
        getMany(request: GrpcContactRequest, metadata?: Metadata): GrpcContactList | Promise<GrpcContactList> | Observable<GrpcContactList> {
          //@ts-ignore
          return this.client.getMany(request, metadata?.clone()).pipe(...proxyPipes);
        }
      }

      return {
        Controller: GrpcContactProxyController,
        service: "ContactService",
      };
    };
  },
  ControllerMethods: (): ClassDecorator => ContactServiceControllerMethods(),
} as const;

