// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/auth/auth.messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { User } from '../user/user';

export interface AuthLogin {
  login: string;
  password: string;
}

export interface AuthRefresh {
  refreshToken: string;
}

export interface AuthToken {
  value: string;
  expiredAt: Date;
}

export interface AuthTokens {
  accessToken: AuthToken;
  refreshToken: AuthToken;
}

export interface AuthData {
  user: User;
  tokens: AuthTokens;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
