export const REDIS_MICROSERVICE_OPTIONS = Symbol('REDIS_MICROSERVICE_OPTIONS');
export const REDIS_CONNECTION = Symbol('REDIS_CONNECTION');
export const REDIS_CLIENT = Symbol('REDIS_CLIENT');
export const REDIS_SUBSCRIPTION_REGISTRY = Symbol('REDIS_SUBSCRIPTION_REGISTRY');
export const REDIS_PARKING = Symbol('REDIS_PARKING');
export const REDIS_MEDIATOR = Symbol('REDIS_MEDIATOR');
export const REDIS_TOPOLOGY = Symbol('REDIS_TOPOLOGY');
