// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/image/image.messages.proto

/* eslint-disable */
import type { StorageManyMeta, StorageMeta } from '../common/common.messages';
import type { FileCreate } from '../file/file.messages';
import type { Image } from './image';
import type { ImagePopulated } from './image.populates';

export interface ImageQuery {
  id?: string;
  ids: string[];
  file?: string;
  userId?: string;
}

export interface ImageList {
  items: ImagePopulated[];
  total: number;
}

export interface ImageArray {
  images: Image[];
}

export interface ImageCreate {
  width: number;
  height: number;
  alt: string;
}

export interface ImageCreateOne {
  image: ImageCreate;
  file: FileCreate;
  storage?: StorageMeta;
  userId: string;
}

export interface ImageCreateOneWeb {
  image: ImageCreate;
  file: FileCreate;
  storage?: StorageMeta;
}

export interface ImageCreateManyItem {
  image: ImageCreate;
  file: FileCreate;
  uploadId: string;
}

export interface ImageCreateMany {
  storage?: StorageManyMeta;
  items: ImageCreateManyItem[];
  userId: string;
}

export interface ImageCreateManyWeb {
  storage?: StorageManyMeta;
  items: ImageCreateManyItem[];
}

export interface ImageUpdateSet {
  alt?: string;
}

export interface ImageUpdate {
  set?: ImageUpdateSet;
}

export interface ImageUpdateOne {
  query: ImageQuery;
  update: ImageUpdate;
}

export interface ImageUpdateById {
  id: string;
  update: ImageUpdate;
}
