// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/models/temp-code.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';

export interface GrpcTempCode {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  userId: string;
  code: string;
  isActive: boolean;
  expiredAt: Date;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
