// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/storage-object/storage-object.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';

export enum StorageObjectType {
  FOLDER = 'FOLDER',
  FILE = 'FILE',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export interface StorageObject {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: StorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  /** A folder's whole subtree; only on the reads that ask for it, and never on a leaf. */
  folderStats?: StorageObjectFolderStats;
}

/**
 * What a folder holds, counted over its whole subtree: its live subfolders at any depth, and the
 * leaves whose upload is READY. `totalSize` is the sum of those leaves' sizes in bytes, a `double`
 * because a sum outgrows `int32` past 2 GiB, and an `int64` reaches Node as a `Long`.
 */
export interface StorageObjectFolderStats {
  fileCount: number;
  folderCount: number;
  totalSize: number;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
