// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: storage/storage-object.service.proto

/* eslint-disable */
export { };
