// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: storage/common/common.messages.proto

/* eslint-disable */

export interface DownloadData {
  url: string;
  fileName: string;
}

export interface DownloadMap {
  entries: Map<string, DownloadData>;
}

export interface DownloadMap_EntriesEntry {
  key: string;
  value: DownloadData;
}

export interface UploadOne {
  id?: string;
  chunk?: Uint8Array<ArrayBufferLike>;
}

export interface StorageMeta {
  name: string;
  isPublic: boolean;
  parent: string;
}

export interface StorageManyMeta {
  isPublic: boolean;
  parent: string;
}

export interface GetUrlMap {
  id?: string;
  ids: string[];
  ip?: string;
  userId: string;
}

export interface GetUrlMapWeb {
  id?: string;
  ids: string[];
  ip?: string;
}
