// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/auth.service.proto

/* eslint-disable */
import {
  CallOptions,
  ChannelCredentials,
  Client,
  ClientOptions,
  ClientUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  ServiceError,
} from '@grpc/grpc-js';
import {
  GrpcAuthData,
  GrpcAuthLogin,
  GrpcAuthMe,
  GrpcAuthRefresh,
  GrpcAuthStreamCode,
} from './messages/auth.messages';
import { GrpcUser } from './models/user';
import 'server-only';

type AuthServiceService = typeof AuthServiceService;
const AuthServiceService = {
  login: {
    path: '/auth.AuthService/login' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthLogin): Buffer =>
      Buffer.from(GrpcAuthLogin.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthLogin => GrpcAuthLogin.decode(value),
    responseSerialize: (value: GrpcAuthData): Buffer =>
      Buffer.from(GrpcAuthData.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcAuthData => GrpcAuthData.decode(value),
  },
  refreshToken: {
    path: '/auth.AuthService/refreshToken' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthRefresh): Buffer =>
      Buffer.from(GrpcAuthRefresh.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthRefresh => GrpcAuthRefresh.decode(value),
    responseSerialize: (value: GrpcAuthData): Buffer =>
      Buffer.from(GrpcAuthData.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcAuthData => GrpcAuthData.decode(value),
  },
  me: {
    path: '/auth.AuthService/me' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthMe): Buffer => Buffer.from(GrpcAuthMe.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthMe => GrpcAuthMe.decode(value),
    responseSerialize: (value: GrpcUser): Buffer => Buffer.from(GrpcUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcUser => GrpcUser.decode(value),
  },
} as const;

export interface GrpcAuthServiceClient extends Client {
  login(
    request: GrpcAuthLogin,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  login(
    request: GrpcAuthLogin,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  login(
    request: GrpcAuthLogin,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
}

export const GrpcAuthServiceClient = makeGenericClientConstructor(
  AuthServiceService,
  'auth.AuthService',
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): GrpcAuthServiceClient;
  service: {
    readonly login: {
      readonly path: '/auth.AuthService/login';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthLogin) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthLogin;
      readonly responseSerialize: (value: GrpcAuthData) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcAuthData;
    };
    readonly refreshToken: {
      readonly path: '/auth.AuthService/refreshToken';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthRefresh) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthRefresh;
      readonly responseSerialize: (value: GrpcAuthData) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcAuthData;
    };
    readonly me: {
      readonly path: '/auth.AuthService/me';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthMe) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthMe;
      readonly responseSerialize: (value: GrpcUser) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcUser;
    };
  };
  serviceName: string;
};

type AuthProxyServiceService = typeof AuthProxyServiceService;
const AuthProxyServiceService = {
  login: {
    path: '/auth.AuthProxyService/login' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthLogin): Buffer =>
      Buffer.from(GrpcAuthLogin.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthLogin => GrpcAuthLogin.decode(value),
    responseSerialize: (value: GrpcAuthData): Buffer =>
      Buffer.from(GrpcAuthData.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcAuthData => GrpcAuthData.decode(value),
  },
  refreshToken: {
    path: '/auth.AuthProxyService/refreshToken' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthRefresh): Buffer =>
      Buffer.from(GrpcAuthRefresh.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthRefresh => GrpcAuthRefresh.decode(value),
    responseSerialize: (value: GrpcAuthData): Buffer =>
      Buffer.from(GrpcAuthData.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcAuthData => GrpcAuthData.decode(value),
  },
  me: {
    path: '/auth.AuthProxyService/me' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthMe): Buffer => Buffer.from(GrpcAuthMe.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthMe => GrpcAuthMe.decode(value),
    responseSerialize: (value: GrpcUser): Buffer => Buffer.from(GrpcUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcUser => GrpcUser.decode(value),
  },
  generateStreamCode: {
    path: '/auth.AuthProxyService/generateStreamCode' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GrpcAuthMe): Buffer => Buffer.from(GrpcAuthMe.encode(value).finish()),
    requestDeserialize: (value: Buffer): GrpcAuthMe => GrpcAuthMe.decode(value),
    responseSerialize: (value: GrpcAuthStreamCode): Buffer =>
      Buffer.from(GrpcAuthStreamCode.encode(value).finish()),
    responseDeserialize: (value: Buffer): GrpcAuthStreamCode => GrpcAuthStreamCode.decode(value),
  },
} as const;

export interface GrpcAuthProxyServiceClient extends Client {
  login(
    request: GrpcAuthLogin,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  login(
    request: GrpcAuthLogin,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  login(
    request: GrpcAuthLogin,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcAuthData) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
  me(
    request: GrpcAuthMe,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcUser) => void,
  ): ClientUnaryCall;
  generateStreamCode(
    request: GrpcAuthMe,
    callback: (error: ServiceError | null, response: GrpcAuthStreamCode) => void,
  ): ClientUnaryCall;
  generateStreamCode(
    request: GrpcAuthMe,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GrpcAuthStreamCode) => void,
  ): ClientUnaryCall;
  generateStreamCode(
    request: GrpcAuthMe,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GrpcAuthStreamCode) => void,
  ): ClientUnaryCall;
}

export const GrpcAuthProxyServiceClient = makeGenericClientConstructor(
  AuthProxyServiceService,
  'auth.AuthProxyService',
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): GrpcAuthProxyServiceClient;
  service: {
    readonly login: {
      readonly path: '/auth.AuthProxyService/login';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthLogin) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthLogin;
      readonly responseSerialize: (value: GrpcAuthData) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcAuthData;
    };
    readonly refreshToken: {
      readonly path: '/auth.AuthProxyService/refreshToken';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthRefresh) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthRefresh;
      readonly responseSerialize: (value: GrpcAuthData) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcAuthData;
    };
    readonly me: {
      readonly path: '/auth.AuthProxyService/me';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthMe) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthMe;
      readonly responseSerialize: (value: GrpcUser) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcUser;
    };
    readonly generateStreamCode: {
      readonly path: '/auth.AuthProxyService/generateStreamCode';
      readonly requestStream: false;
      readonly responseStream: false;
      readonly requestSerialize: (value: GrpcAuthMe) => Buffer;
      readonly requestDeserialize: (value: Buffer) => GrpcAuthMe;
      readonly responseSerialize: (value: GrpcAuthStreamCode) => Buffer;
      readonly responseDeserialize: (value: Buffer) => GrpcAuthStreamCode;
    };
  };
  serviceName: string;
};

export class GrpcAuthRepository {
  protected readonly client: GrpcAuthServiceClient;

  constructor(
    address: string,
    credentials: ChannelCredentials = ChannelCredentials.createInsecure(),
    options?: Partial<ClientOptions>,
  ) {
    this.client = new GrpcAuthServiceClient(address, credentials, options);
  }

  getClient(): GrpcAuthServiceClient {
    return this.client;
  }

  login(
    request: GrpcAuthLogin,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcAuthData> {
    return new Promise<GrpcAuthData>((resolve, reject) => {
      this.client.login(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcAuthData> {
    return new Promise<GrpcAuthData>((resolve, reject) => {
      this.client.refreshToken(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  me(
    request: GrpcAuthMe,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcUser> {
    return new Promise<GrpcUser>((resolve, reject) => {
      this.client.me(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }
}

export class GrpcAuthProxyRepository {
  protected readonly client: GrpcAuthProxyServiceClient;

  constructor(
    address: string,
    credentials: ChannelCredentials = ChannelCredentials.createInsecure(),
    options?: Partial<ClientOptions>,
  ) {
    this.client = new GrpcAuthProxyServiceClient(address, credentials, options);
  }

  getClient(): GrpcAuthProxyServiceClient {
    return this.client;
  }

  login(
    request: GrpcAuthLogin,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcAuthData> {
    return new Promise<GrpcAuthData>((resolve, reject) => {
      this.client.login(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  refreshToken(
    request: GrpcAuthRefresh,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcAuthData> {
    return new Promise<GrpcAuthData>((resolve, reject) => {
      this.client.refreshToken(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  me(
    request: GrpcAuthMe,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcUser> {
    return new Promise<GrpcUser>((resolve, reject) => {
      this.client.me(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }

  generateStreamCode(
    request: GrpcAuthMe,
    metadata: Metadata = new Metadata(),
    options: Partial<CallOptions> = {},
  ): Promise<GrpcAuthStreamCode> {
    return new Promise<GrpcAuthStreamCode>((resolve, reject) => {
      this.client.generateStreamCode(request, metadata, options, (err, response) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
  }
}
