// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: common/crud.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import "server-only";

export enum GrpcCrudLogicalOperator {
  eq = "eq",
  ne = "ne",
  eqs = "eqs",
  nes = "nes",
  lt = "lt",
  gt = "gt",
  lte = "lte",
  gte = "gte",
  in = "in",
  nin = "nin",
  ina = "ina",
  nina = "nina",
  contains = "contains",
  ncontains = "ncontains",
  containss = "containss",
  ncontainss = "ncontainss",
  between = "between",
  nbetween = "nbetween",
  null = "null",
  nnull = "nnull",
  startswith = "startswith",
  nstartswith = "nstartswith",
  startswiths = "startswiths",
  nstartswiths = "nstartswiths",
  endswith = "endswith",
  nendswith = "nendswith",
  endswiths = "endswiths",
  nendswiths = "nendswiths",
}

export function grpcCrudLogicalOperatorFromJSON(object: any): GrpcCrudLogicalOperator {
  switch (object) {
    case 0:
    case "eq":
      return GrpcCrudLogicalOperator.eq;
    case 1:
    case "ne":
      return GrpcCrudLogicalOperator.ne;
    case 2:
    case "eqs":
      return GrpcCrudLogicalOperator.eqs;
    case 3:
    case "nes":
      return GrpcCrudLogicalOperator.nes;
    case 4:
    case "lt":
      return GrpcCrudLogicalOperator.lt;
    case 5:
    case "gt":
      return GrpcCrudLogicalOperator.gt;
    case 6:
    case "lte":
      return GrpcCrudLogicalOperator.lte;
    case 7:
    case "gte":
      return GrpcCrudLogicalOperator.gte;
    case 8:
    case "in":
      return GrpcCrudLogicalOperator.in;
    case 9:
    case "nin":
      return GrpcCrudLogicalOperator.nin;
    case 10:
    case "ina":
      return GrpcCrudLogicalOperator.ina;
    case 11:
    case "nina":
      return GrpcCrudLogicalOperator.nina;
    case 12:
    case "contains":
      return GrpcCrudLogicalOperator.contains;
    case 13:
    case "ncontains":
      return GrpcCrudLogicalOperator.ncontains;
    case 14:
    case "containss":
      return GrpcCrudLogicalOperator.containss;
    case 15:
    case "ncontainss":
      return GrpcCrudLogicalOperator.ncontainss;
    case 16:
    case "between":
      return GrpcCrudLogicalOperator.between;
    case 17:
    case "nbetween":
      return GrpcCrudLogicalOperator.nbetween;
    case 18:
    case "null":
      return GrpcCrudLogicalOperator.null;
    case 19:
    case "nnull":
      return GrpcCrudLogicalOperator.nnull;
    case 20:
    case "startswith":
      return GrpcCrudLogicalOperator.startswith;
    case 21:
    case "nstartswith":
      return GrpcCrudLogicalOperator.nstartswith;
    case 22:
    case "startswiths":
      return GrpcCrudLogicalOperator.startswiths;
    case 23:
    case "nstartswiths":
      return GrpcCrudLogicalOperator.nstartswiths;
    case 24:
    case "endswith":
      return GrpcCrudLogicalOperator.endswith;
    case 25:
    case "nendswith":
      return GrpcCrudLogicalOperator.nendswith;
    case 26:
    case "endswiths":
      return GrpcCrudLogicalOperator.endswiths;
    case 27:
    case "nendswiths":
      return GrpcCrudLogicalOperator.nendswiths;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudLogicalOperator");
  }
}

export function grpcCrudLogicalOperatorToJSON(object: GrpcCrudLogicalOperator): string {
  switch (object) {
    case GrpcCrudLogicalOperator.eq:
      return "eq";
    case GrpcCrudLogicalOperator.ne:
      return "ne";
    case GrpcCrudLogicalOperator.eqs:
      return "eqs";
    case GrpcCrudLogicalOperator.nes:
      return "nes";
    case GrpcCrudLogicalOperator.lt:
      return "lt";
    case GrpcCrudLogicalOperator.gt:
      return "gt";
    case GrpcCrudLogicalOperator.lte:
      return "lte";
    case GrpcCrudLogicalOperator.gte:
      return "gte";
    case GrpcCrudLogicalOperator.in:
      return "in";
    case GrpcCrudLogicalOperator.nin:
      return "nin";
    case GrpcCrudLogicalOperator.ina:
      return "ina";
    case GrpcCrudLogicalOperator.nina:
      return "nina";
    case GrpcCrudLogicalOperator.contains:
      return "contains";
    case GrpcCrudLogicalOperator.ncontains:
      return "ncontains";
    case GrpcCrudLogicalOperator.containss:
      return "containss";
    case GrpcCrudLogicalOperator.ncontainss:
      return "ncontainss";
    case GrpcCrudLogicalOperator.between:
      return "between";
    case GrpcCrudLogicalOperator.nbetween:
      return "nbetween";
    case GrpcCrudLogicalOperator.null:
      return "null";
    case GrpcCrudLogicalOperator.nnull:
      return "nnull";
    case GrpcCrudLogicalOperator.startswith:
      return "startswith";
    case GrpcCrudLogicalOperator.nstartswith:
      return "nstartswith";
    case GrpcCrudLogicalOperator.startswiths:
      return "startswiths";
    case GrpcCrudLogicalOperator.nstartswiths:
      return "nstartswiths";
    case GrpcCrudLogicalOperator.endswith:
      return "endswith";
    case GrpcCrudLogicalOperator.nendswith:
      return "nendswith";
    case GrpcCrudLogicalOperator.endswiths:
      return "endswiths";
    case GrpcCrudLogicalOperator.nendswiths:
      return "nendswiths";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudLogicalOperator");
  }
}

export function grpcCrudLogicalOperatorToNumber(object: GrpcCrudLogicalOperator): number {
  switch (object) {
    case GrpcCrudLogicalOperator.eq:
      return 0;
    case GrpcCrudLogicalOperator.ne:
      return 1;
    case GrpcCrudLogicalOperator.eqs:
      return 2;
    case GrpcCrudLogicalOperator.nes:
      return 3;
    case GrpcCrudLogicalOperator.lt:
      return 4;
    case GrpcCrudLogicalOperator.gt:
      return 5;
    case GrpcCrudLogicalOperator.lte:
      return 6;
    case GrpcCrudLogicalOperator.gte:
      return 7;
    case GrpcCrudLogicalOperator.in:
      return 8;
    case GrpcCrudLogicalOperator.nin:
      return 9;
    case GrpcCrudLogicalOperator.ina:
      return 10;
    case GrpcCrudLogicalOperator.nina:
      return 11;
    case GrpcCrudLogicalOperator.contains:
      return 12;
    case GrpcCrudLogicalOperator.ncontains:
      return 13;
    case GrpcCrudLogicalOperator.containss:
      return 14;
    case GrpcCrudLogicalOperator.ncontainss:
      return 15;
    case GrpcCrudLogicalOperator.between:
      return 16;
    case GrpcCrudLogicalOperator.nbetween:
      return 17;
    case GrpcCrudLogicalOperator.null:
      return 18;
    case GrpcCrudLogicalOperator.nnull:
      return 19;
    case GrpcCrudLogicalOperator.startswith:
      return 20;
    case GrpcCrudLogicalOperator.nstartswith:
      return 21;
    case GrpcCrudLogicalOperator.startswiths:
      return 22;
    case GrpcCrudLogicalOperator.nstartswiths:
      return 23;
    case GrpcCrudLogicalOperator.endswith:
      return 24;
    case GrpcCrudLogicalOperator.nendswith:
      return 25;
    case GrpcCrudLogicalOperator.endswiths:
      return 26;
    case GrpcCrudLogicalOperator.nendswiths:
      return 27;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudLogicalOperator");
  }
}

export enum GrpcCrudConditionalOperator {
  or = "or",
  and = "and",
}

export function grpcCrudConditionalOperatorFromJSON(object: any): GrpcCrudConditionalOperator {
  switch (object) {
    case 0:
    case "or":
      return GrpcCrudConditionalOperator.or;
    case 1:
    case "and":
      return GrpcCrudConditionalOperator.and;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudConditionalOperator");
  }
}

export function grpcCrudConditionalOperatorToJSON(object: GrpcCrudConditionalOperator): string {
  switch (object) {
    case GrpcCrudConditionalOperator.or:
      return "or";
    case GrpcCrudConditionalOperator.and:
      return "and";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudConditionalOperator");
  }
}

export function grpcCrudConditionalOperatorToNumber(object: GrpcCrudConditionalOperator): number {
  switch (object) {
    case GrpcCrudConditionalOperator.or:
      return 0;
    case GrpcCrudConditionalOperator.and:
      return 1;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudConditionalOperator");
  }
}

export enum GrpcCrudSort {
  asc = "asc",
  desc = "desc",
}

export function grpcCrudSortFromJSON(object: any): GrpcCrudSort {
  switch (object) {
    case 0:
    case "asc":
      return GrpcCrudSort.asc;
    case 1:
    case "desc":
      return GrpcCrudSort.desc;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudSort");
  }
}

export function grpcCrudSortToJSON(object: GrpcCrudSort): string {
  switch (object) {
    case GrpcCrudSort.asc:
      return "asc";
    case GrpcCrudSort.desc:
      return "desc";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudSort");
  }
}

export function grpcCrudSortToNumber(object: GrpcCrudSort): number {
  switch (object) {
    case GrpcCrudSort.asc:
      return 0;
    case GrpcCrudSort.desc:
      return 1;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum GrpcCrudSort");
  }
}

export interface GrpcCrudLogicalFilter {
  field: string;
  operator: GrpcCrudLogicalOperator;
  string?: string;
  number?: number;
  boolean?: boolean;
}

export interface GrpcCrudConditionalFilter {
  key?: string;
  operator: GrpcCrudConditionalOperator;
  value: GrpcCrudLogicalFilter[];
}

export interface GrpcCrudSorter {
  field: string;
  order: GrpcCrudSort;
}

function createBaseGrpcCrudLogicalFilter(): GrpcCrudLogicalFilter {
  return { field: "", operator: GrpcCrudLogicalOperator.eq, string: undefined, number: undefined, boolean: undefined };
}

export const GrpcCrudLogicalFilter: MessageFns<GrpcCrudLogicalFilter> = {
  encode(message: GrpcCrudLogicalFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    if (message.operator !== GrpcCrudLogicalOperator.eq) {
      writer.uint32(16).int32(grpcCrudLogicalOperatorToNumber(message.operator));
    }
    if (message.string !== undefined) {
      writer.uint32(26).string(message.string);
    }
    if (message.number !== undefined) {
      writer.uint32(32).int32(message.number);
    }
    if (message.boolean !== undefined) {
      writer.uint32(40).bool(message.boolean);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcCrudLogicalFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcCrudLogicalFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.field = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operator = grpcCrudLogicalOperatorFromJSON(reader.int32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.string = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.number = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.boolean = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcCrudLogicalFilter {
    return {
      field: isSet(object.field) ? globalThis.String(object.field) : "",
      operator: isSet(object.operator) ? grpcCrudLogicalOperatorFromJSON(object.operator) : GrpcCrudLogicalOperator.eq,
      string: isSet(object.string) ? globalThis.String(object.string) : undefined,
      number: isSet(object.number) ? globalThis.Number(object.number) : undefined,
      boolean: isSet(object.boolean) ? globalThis.Boolean(object.boolean) : undefined,
    };
  },

  toJSON(message: GrpcCrudLogicalFilter): unknown {
    const obj: any = {};
    if (message.field !== "") {
      obj.field = message.field;
    }
    if (message.operator !== GrpcCrudLogicalOperator.eq) {
      obj.operator = grpcCrudLogicalOperatorToJSON(message.operator);
    }
    if (message.string !== undefined) {
      obj.string = message.string;
    }
    if (message.number !== undefined) {
      obj.number = Math.round(message.number);
    }
    if (message.boolean !== undefined) {
      obj.boolean = message.boolean;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcCrudLogicalFilter>, I>>(base?: I): GrpcCrudLogicalFilter {
    return GrpcCrudLogicalFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcCrudLogicalFilter>, I>>(object: I): GrpcCrudLogicalFilter {
    const message = createBaseGrpcCrudLogicalFilter();
    message.field = object.field ?? "";
    message.operator = object.operator ?? GrpcCrudLogicalOperator.eq;
    message.string = object.string ?? undefined;
    message.number = object.number ?? undefined;
    message.boolean = object.boolean ?? undefined;
    return message;
  },
};

function createBaseGrpcCrudConditionalFilter(): GrpcCrudConditionalFilter {
  return { key: undefined, operator: GrpcCrudConditionalOperator.or, value: [] };
}

export const GrpcCrudConditionalFilter: MessageFns<GrpcCrudConditionalFilter> = {
  encode(message: GrpcCrudConditionalFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      writer.uint32(10).string(message.key);
    }
    if (message.operator !== GrpcCrudConditionalOperator.or) {
      writer.uint32(16).int32(grpcCrudConditionalOperatorToNumber(message.operator));
    }
    for (const v of message.value) {
      GrpcCrudLogicalFilter.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcCrudConditionalFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcCrudConditionalFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operator = grpcCrudConditionalOperatorFromJSON(reader.int32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.value.push(GrpcCrudLogicalFilter.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcCrudConditionalFilter {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      operator: isSet(object.operator)
        ? grpcCrudConditionalOperatorFromJSON(object.operator)
        : GrpcCrudConditionalOperator.or,
      value: globalThis.Array.isArray(object?.value)
        ? object.value.map((e: any) => GrpcCrudLogicalFilter.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GrpcCrudConditionalFilter): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.operator !== GrpcCrudConditionalOperator.or) {
      obj.operator = grpcCrudConditionalOperatorToJSON(message.operator);
    }
    if (message.value?.length) {
      obj.value = message.value.map((e) => GrpcCrudLogicalFilter.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcCrudConditionalFilter>, I>>(base?: I): GrpcCrudConditionalFilter {
    return GrpcCrudConditionalFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcCrudConditionalFilter>, I>>(object: I): GrpcCrudConditionalFilter {
    const message = createBaseGrpcCrudConditionalFilter();
    message.key = object.key ?? undefined;
    message.operator = object.operator ?? GrpcCrudConditionalOperator.or;
    message.value = object.value?.map((e) => GrpcCrudLogicalFilter.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrpcCrudSorter(): GrpcCrudSorter {
  return { field: "", order: GrpcCrudSort.asc };
}

export const GrpcCrudSorter: MessageFns<GrpcCrudSorter> = {
  encode(message: GrpcCrudSorter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    if (message.order !== GrpcCrudSort.asc) {
      writer.uint32(16).int32(grpcCrudSortToNumber(message.order));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrpcCrudSorter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrpcCrudSorter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.field = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.order = grpcCrudSortFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GrpcCrudSorter {
    return {
      field: isSet(object.field) ? globalThis.String(object.field) : "",
      order: isSet(object.order) ? grpcCrudSortFromJSON(object.order) : GrpcCrudSort.asc,
    };
  },

  toJSON(message: GrpcCrudSorter): unknown {
    const obj: any = {};
    if (message.field !== "") {
      obj.field = message.field;
    }
    if (message.order !== GrpcCrudSort.asc) {
      obj.order = grpcCrudSortToJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GrpcCrudSorter>, I>>(base?: I): GrpcCrudSorter {
    return GrpcCrudSorter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrpcCrudSorter>, I>>(object: I): GrpcCrudSorter {
    const message = createBaseGrpcCrudSorter();
    message.field = object.field ?? "";
    message.order = object.order ?? GrpcCrudSort.asc;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
