// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/auth/auth.messages.proto

/* eslint-disable */
import type { User } from '../user/user';

export interface AuthLogin {
  login: string;
  password: string;
}

export interface AuthRefresh {
  refreshToken: string;
}

export interface AuthToken {
  value: string;
  expiredAt: Date;
}

export interface AuthTokens {
  accessToken: AuthToken;
  refreshToken: AuthToken;
}

export interface AuthData {
  user: User;
  tokens: AuthTokens;
}
