// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: auth/messages/user.messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { User, UserRole, userRoleFromJSON, userRoleToJSON, userRoleToNumber } from '../models/user';

export interface UserQuery {
  id?: string;
  ids: string[];
  email?: string;
  roles: UserRole[];
}

export interface UserRequest {
  query: UserQuery;
}

export interface UserList {
  items: User[];
}

export interface UserGetListResponse {
  items: User[];
  total: number;
}

export interface UserCreate {
  email: string;
  password: string;
  role?: UserRole;
}

export interface UserCreateManyRequest {
  items: UserCreate[];
}

export interface UserUpdateSet {
  email?: string;
  role?: UserRole;
  password?: string;
}

export interface UserUpdate {
  set?: UserUpdateSet;
}

export interface UserUpdateRequest {
  query: UserQuery;
  update: UserUpdate;
}

export interface UserUpdateByIdRequest {
  id: string;
  update: UserUpdate;
}

function createBaseUserQuery(): UserQuery {
  return { id: undefined, ids: [], email: undefined, roles: [] };
}

export const UserQuery: MessageFns<UserQuery> = {
  encode(message: UserQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    if (message.email !== undefined) {
      writer.uint32(26).string(message.email);
    }
    writer.uint32(34).fork();
    for (const v of message.roles) {
      writer.int32(userRoleToNumber(v));
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.roles.push(userRoleFromJSON(reader.int32()));

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.roles.push(userRoleFromJSON(reader.int32()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserQuery {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      ids: globalThis.Array.isArray(object?.ids)
        ? object.ids.map((e: any) => globalThis.String(e))
        : [],
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => userRoleFromJSON(e))
        : [],
    };
  },

  toJSON(message: UserQuery): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.roles?.length) {
      obj.roles = message.roles.map((e) => userRoleToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserQuery>, I>>(base?: I): UserQuery {
    return UserQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserQuery>, I>>(object: I): UserQuery {
    const message = createBaseUserQuery();
    message.id = object.id ?? undefined;
    message.ids = object.ids?.map((e) => e) || [];
    message.email = object.email ?? undefined;
    message.roles = object.roles?.map((e) => e) || [];
    return message;
  },
};

function createBaseUserRequest(): UserRequest {
  return { query: undefined };
}

export const UserRequest: MessageFns<UserRequest> = {
  encode(message: UserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      UserQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = UserQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRequest {
    return { query: isSet(object.query) ? UserQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: UserRequest): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = UserQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRequest>, I>>(base?: I): UserRequest {
    return UserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRequest>, I>>(object: I): UserRequest {
    const message = createBaseUserRequest();
    message.query =
      object.query !== undefined && object.query !== null
        ? UserQuery.fromPartial(object.query)
        : undefined;
    return message;
  },
};

function createBaseUserList(): UserList {
  return { items: [] };
}

export const UserList: MessageFns<UserList> = {
  encode(message: UserList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      User.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(User.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserList {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => User.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserList): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => User.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserList>, I>>(base?: I): UserList {
    return UserList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserList>, I>>(object: I): UserList {
    const message = createBaseUserList();
    message.items = object.items?.map((e) => User.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUserGetListResponse(): UserGetListResponse {
  return { items: [], total: 0 };
}

export const UserGetListResponse: MessageFns<UserGetListResponse> = {
  encode(message: UserGetListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      User.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserGetListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserGetListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(User.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserGetListResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => User.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: UserGetListResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => User.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserGetListResponse>, I>>(base?: I): UserGetListResponse {
    return UserGetListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserGetListResponse>, I>>(
    object: I,
  ): UserGetListResponse {
    const message = createBaseUserGetListResponse();
    message.items = object.items?.map((e) => User.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseUserCreate(): UserCreate {
  return { email: '', password: '', role: undefined };
}

export const UserCreate: MessageFns<UserCreate> = {
  encode(message: UserCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== '') {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== '') {
      writer.uint32(18).string(message.password);
    }
    if (message.role !== undefined) {
      writer.uint32(24).int32(userRoleToNumber(message.role));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = userRoleFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserCreate {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      password: isSet(object.password) ? globalThis.String(object.password) : '',
      role: isSet(object.role) ? userRoleFromJSON(object.role) : undefined,
    };
  },

  toJSON(message: UserCreate): unknown {
    const obj: any = {};
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    if (message.role !== undefined) {
      obj.role = userRoleToJSON(message.role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserCreate>, I>>(base?: I): UserCreate {
    return UserCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserCreate>, I>>(object: I): UserCreate {
    const message = createBaseUserCreate();
    message.email = object.email ?? '';
    message.password = object.password ?? '';
    message.role = object.role ?? undefined;
    return message;
  },
};

function createBaseUserCreateManyRequest(): UserCreateManyRequest {
  return { items: [] };
}

export const UserCreateManyRequest: MessageFns<UserCreateManyRequest> = {
  encode(message: UserCreateManyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      UserCreate.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserCreateManyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserCreateManyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(UserCreate.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserCreateManyRequest {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => UserCreate.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserCreateManyRequest): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => UserCreate.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserCreateManyRequest>, I>>(base?: I): UserCreateManyRequest {
    return UserCreateManyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserCreateManyRequest>, I>>(
    object: I,
  ): UserCreateManyRequest {
    const message = createBaseUserCreateManyRequest();
    message.items = object.items?.map((e) => UserCreate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUserUpdateSet(): UserUpdateSet {
  return { email: undefined, role: undefined, password: undefined };
}

export const UserUpdateSet: MessageFns<UserUpdateSet> = {
  encode(message: UserUpdateSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== undefined) {
      writer.uint32(10).string(message.email);
    }
    if (message.role !== undefined) {
      writer.uint32(16).int32(userRoleToNumber(message.role));
    }
    if (message.password !== undefined) {
      writer.uint32(26).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserUpdateSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserUpdateSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = userRoleFromJSON(reader.int32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserUpdateSet {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      role: isSet(object.role) ? userRoleFromJSON(object.role) : undefined,
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
    };
  },

  toJSON(message: UserUpdateSet): unknown {
    const obj: any = {};
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.role !== undefined) {
      obj.role = userRoleToJSON(message.role);
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserUpdateSet>, I>>(base?: I): UserUpdateSet {
    return UserUpdateSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserUpdateSet>, I>>(object: I): UserUpdateSet {
    const message = createBaseUserUpdateSet();
    message.email = object.email ?? undefined;
    message.role = object.role ?? undefined;
    message.password = object.password ?? undefined;
    return message;
  },
};

function createBaseUserUpdate(): UserUpdate {
  return { set: undefined };
}

export const UserUpdate: MessageFns<UserUpdate> = {
  encode(message: UserUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.set !== undefined) {
      UserUpdateSet.encode(message.set, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.set = UserUpdateSet.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserUpdate {
    return { set: isSet(object.set) ? UserUpdateSet.fromJSON(object.set) : undefined };
  },

  toJSON(message: UserUpdate): unknown {
    const obj: any = {};
    if (message.set !== undefined) {
      obj.set = UserUpdateSet.toJSON(message.set);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserUpdate>, I>>(base?: I): UserUpdate {
    return UserUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserUpdate>, I>>(object: I): UserUpdate {
    const message = createBaseUserUpdate();
    message.set =
      object.set !== undefined && object.set !== null
        ? UserUpdateSet.fromPartial(object.set)
        : undefined;
    return message;
  },
};

function createBaseUserUpdateRequest(): UserUpdateRequest {
  return { query: undefined, update: undefined };
}

export const UserUpdateRequest: MessageFns<UserUpdateRequest> = {
  encode(message: UserUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      UserQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    if (message.update !== undefined) {
      UserUpdate.encode(message.update, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = UserQuery.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.update = UserUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserUpdateRequest {
    return {
      query: isSet(object.query) ? UserQuery.fromJSON(object.query) : undefined,
      update: isSet(object.update) ? UserUpdate.fromJSON(object.update) : undefined,
    };
  },

  toJSON(message: UserUpdateRequest): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = UserQuery.toJSON(message.query);
    }
    if (message.update !== undefined) {
      obj.update = UserUpdate.toJSON(message.update);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserUpdateRequest>, I>>(base?: I): UserUpdateRequest {
    return UserUpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserUpdateRequest>, I>>(object: I): UserUpdateRequest {
    const message = createBaseUserUpdateRequest();
    message.query =
      object.query !== undefined && object.query !== null
        ? UserQuery.fromPartial(object.query)
        : undefined;
    message.update =
      object.update !== undefined && object.update !== null
        ? UserUpdate.fromPartial(object.update)
        : undefined;
    return message;
  },
};

function createBaseUserUpdateByIdRequest(): UserUpdateByIdRequest {
  return { id: '', update: undefined };
}

export const UserUpdateByIdRequest: MessageFns<UserUpdateByIdRequest> = {
  encode(message: UserUpdateByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.update !== undefined) {
      UserUpdate.encode(message.update, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserUpdateByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserUpdateByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.update = UserUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserUpdateByIdRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      update: isSet(object.update) ? UserUpdate.fromJSON(object.update) : undefined,
    };
  },

  toJSON(message: UserUpdateByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.update !== undefined) {
      obj.update = UserUpdate.toJSON(message.update);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserUpdateByIdRequest>, I>>(base?: I): UserUpdateByIdRequest {
    return UserUpdateByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserUpdateByIdRequest>, I>>(
    object: I,
  ): UserUpdateByIdRequest {
    const message = createBaseUserUpdateByIdRequest();
    message.id = object.id ?? '';
    message.update =
      object.update !== undefined && object.update !== null
        ? UserUpdate.fromPartial(object.update)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
