// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v7.34.0
// source: storage/models/file.proto

/* eslint-disable */
import { wrappers } from "protobufjs";

export enum GrpcFileUploadStatus {
  PENDING = "PENDING",
  FAILED = "FAILED",
  READY = "READY",
}

export interface GrpcFile {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  originalName: string;
  size: number;
  mimeType: string;
  extension: string;
  uploadStatus: GrpcFileUploadStatus;
  providerId?: string;
  userId: string;
  uploadId: string;
}

const STORAGE_MODELS_PACKAGE_NAME = "storage.models";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
