// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/messages/storage-object.messages.proto

/* eslint-disable */
import type { GrpcBaseQuery } from "../../common/service";
import type { GrpcFile } from "../models/file";
import type { GrpcImage } from "../models/image";
import type { GrpcStorageObjectType } from "../models/storage-object";
import type { GrpcVideo } from "../models/video";

export interface GrpcStorageObjectPopulated {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: GrpcStorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  file?: GrpcFile;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  image?: GrpcImage;
  video?: GrpcVideo;
}

export interface GrpcStorageObjectQuery {
  id?: string;
  ids: string[];
  type?: GrpcStorageObjectType;
  userId?: string;
  isPublic?: boolean;
  parent?: string;
  file?: string;
  name?: string;
}

export interface GrpcStorageObjectRequest {
  query: GrpcStorageObjectQuery;
}

export interface GrpcStorageObjectList {
  items: GrpcStorageObjectPopulated[];
}

export interface GrpcStorageObjectGetListResponse {
  items: GrpcStorageObjectPopulated[];
  total: number;
}

export interface GrpcStorageObjectExistsFolderRequest {
  parent: string;
  name: string;
}

export interface GrpcStorageObjectGetFoldersRequest {
  id?: string;
}

export interface GrpcStorageObjectGetFoldersItem {
  id: string;
  folderPath: string;
}

export interface GrpcStorageObjectGetFoldersResponse {
  items: GrpcStorageObjectGetFoldersItem[];
}

export interface GrpcStorageObjectCreate {
  name: string;
  isPublic: boolean;
  parent?: string;
  type: GrpcStorageObjectType;
  file?: string;
  image?: string;
  video?: string;
}

export interface GrpcStorageObjectMetadata {
  name: string;
  isPublic: boolean;
  parent: string;
}

export interface GrpcStorageObjectManyMetadata {
  isPublic: boolean;
  parent: string;
}

export interface GrpcStorageObjectUpdateSet {
  name?: string;
  isPublic?: boolean;
  parent?: string;
}

export interface GrpcStorageObjectUpdate {
  set?: GrpcStorageObjectUpdateSet;
}

export interface GrpcStorageObjectUpdateRequest {
  query: GrpcBaseQuery;
  update: GrpcStorageObjectUpdate;
}

export interface GrpcStorageObjectUpdateByIdRequest {
  id: string;
  update: GrpcStorageObjectUpdate;
}
