// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/common/common.messages.proto

/* eslint-disable */

export interface DownloadData {
  url: string;
  fileName: string;
}

export interface DownloadMap {
  entries: { [key: string]: DownloadData };
}

export interface DownloadMapEntriesEntry {
  key: string;
  value: DownloadData;
}

export interface StorageMeta {
  name: string;
  isPublic: boolean;
  parent: string;
}

export interface StorageManyMeta {
  isPublic: boolean;
  parent: string;
}

export interface GetUrlMap {
  id?: string;
  ids: string[];
  ip?: string;
  userId?: string;
}

export interface GetUrlMapShort {
  id?: string;
  ids: string[];
  ip?: string;
}
