// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: storage/file/file.messages.proto

/* eslint-disable */
import type { StorageManyMeta, StorageMeta } from '../common/common.messages';
import type { File, FileUploadStatus } from './file';

export interface FileQuery {
  id?: string;
  ids: string[];
  mimeType?: string;
  mimeTypes: string[];
  userId?: string;
  userIds: string[];
  extension?: string;
  uploadStatus?: FileUploadStatus;
  uploadStatuses: FileUploadStatus[];
  createdAfter?: Date;
}

export interface FileList {
  items: File[];
  total: number;
}

export interface FileArray {
  files: File[];
}

export interface FileCreate {
  originalName: string;
  size: number;
  mimeType: string;
}

export interface FileCreateOne {
  file: FileCreate;
  storage?: StorageMeta;
  userId: string;
}

export interface FileCreateOneWeb {
  file: FileCreate;
  storage?: StorageMeta;
}

export interface FileCreateManyItem {
  file: FileCreate;
  uploadId: string;
}

export interface FileCreateMany {
  storage?: StorageManyMeta;
  items: FileCreateManyItem[];
  userId: string;
}

export interface FileCreateManyWeb {
  storage?: StorageManyMeta;
  items: FileCreateManyItem[];
}

export interface FileUploadResponse {
  entity?: File;
  canSendChunks?: boolean;
  ack?: boolean;
}
