// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/file/file.messages.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';
import { StorageManyMeta, StorageMeta } from '../common/common.messages';
import { File, FileUploadStatus } from './file';

export interface FileQuery {
  id?: string;
  ids: string[];
  mimeType?: string;
  mimeTypes: string[];
  userId?: string;
  userIds: string[];
  extension?: string;
  uploadStatus?: FileUploadStatus;
  uploadStatuses: FileUploadStatus[];
  createdBefore?: Date;
}

export interface FileList {
  items: File[];
  total: number;
}

export interface FileArray {
  items: File[];
}

export interface FileCreate {
  originalName: string;
  size: number;
  mimeType: string;
}

export interface FileCreateOne {
  file: FileCreate;
  storage?: StorageMeta;
  userId: string;
}

export interface FileCreateOneWeb {
  file: FileCreate;
  storage?: StorageMeta;
}

export interface FileCreateManyItem {
  file: FileCreate;
  uploadId: string;
}

export interface FileCreateMany {
  storage?: StorageManyMeta;
  items: FileCreateManyItem[];
  userId: string;
}

export interface FileCreateManyWeb {
  storage?: StorageManyMeta;
  items: FileCreateManyItem[];
}

/**
 * Pre-signed credentials for a direct browser -> Bunny Storage PUT over its S3 API.
 * The browser sends the file as the body of a PUT to `url` with `Content-Type: contentType` (a
 * signed header, like the length), then calls `completeUpload` — Bunny Storage reports nothing
 * back on its own. `expires` is unix seconds.
 */
export interface FilePresignedUpload {
  url: string;
  contentType: string;
  expires: string;
}

export interface FileCreated {
  file: File;
  upload: FilePresignedUpload;
}

export interface FileCreatedArray {
  items: FileCreated[];
}

export interface FileCompleteUpload {
  id: string;
  userId?: string;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
