// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/file/file.proto

/* eslint-disable */
import { wrappers } from 'protobufjs';

/**
 * UPLOADED sits between PENDING and READY: the bytes reached the provider but it has not finished
 * processing them yet. Only videos use it — Bunny's encode takes up to ~33 minutes, and without it
 * "still encoding" and "upload died" are the same state. Appended rather than inserted at 2: the
 * declaration order drives the generated member order and the value list in the CHECK constraint.
 */
export enum FileUploadStatus {
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  READY = 'READY',
  UPLOADED = 'UPLOADED',
}

export interface File {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  originalName: string;
  size: number;
  mimeType: string;
  extension: string;
  uploadStatus: FileUploadStatus;
  providerId?: string;
  userId: string;
  /**
   * The key of the object a grid shows for a plain file: the first page of a PDF, as a small webp
   * made after upload. Unset until that is done, on any other file, and on one it cannot be made for
   * (ADR-0032). An image's is `Image.previewProviderId`.
   */
  previewProviderId?: string;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
