// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/storage-object/storage-object.messages.proto

/* eslint-disable */
import type { Sort } from '../../common/crud';
import type { Pagination } from '../../common/messages';
import type { StorageObject, StorageObjectType } from './storage-object';
import type { StorageObjectFolderItem, StorageObjectPopulated } from './storage-object.populates';

/** What a folder listing sorts by, after folders, which always come first. */
export enum StorageObjectSortField {
  NAME = 'NAME',
  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
  TYPE = 'TYPE',
}

export interface StorageObjectQuery {
  id?: string;
  ids: string[];
  type?: StorageObjectType;
  userId?: string;
  isPublic?: boolean;
  parent?: string;
  file?: string;
  name?: string;
}

export interface StorageObjectQueryWeb {
  id?: string;
  ids: string[];
  type?: StorageObjectType;
  isPublic?: boolean;
  parent?: string;
  name?: string;
}

export interface StorageObjectList {
  items: StorageObjectPopulated[];
  total: number;
}

export interface StorageObjectArray {
  items: StorageObjectPopulated[];
}

export interface StorageObjectGet {
  query?: StorageObjectQuery;
}

export interface StorageObjectGetFolders {
  excludeChildrenOf?: string;
  userId: string;
}

export interface StorageObjectGetFoldersWeb {
  excludeChildrenOf?: string;
}

export interface StorageObjectSorter {
  field: StorageObjectSortField;
  order: Sort;
}

/**
 * Narrows a folder listing. The folder, its owner and "live objects only" are fixed by the server,
 * never by the caller: free-form list filters could override them.
 */
export interface StorageObjectFolderContentQuery {
  types: StorageObjectType[];
  isPublic?: boolean;
  /** A case-insensitive substring of the name. */
  search?: string;
}

export interface StorageObjectGetFolderContent {
  parentId: string;
  userId: string;
  query?: StorageObjectFolderContentQuery;
  sorters: StorageObjectSorter[];
  pagination?: Pagination;
}

export interface StorageObjectGetFolderContentWeb {
  parentId: string;
  query?: StorageObjectFolderContentQuery;
  sorters: StorageObjectSorter[];
  pagination?: Pagination;
}

export interface StorageObjectAncestor {
  id: string;
  name: string;
}

/**
 * A page of a folder's live objects: folders first, then `sorters` (the name when there are none),
 * the id last. `folder` carries its `folderPath`; `ancestors` run from the root (whose name is empty)
 * down to the folder's parent, none for the root itself. Items carry their file, image or video, but
 * no `folderPath`: a subfolder's is the folder's own followed by its name. A READY image or video
 * also carries a signed `previewUrl`.
 */
export interface StorageObjectFolderContent {
  folder: StorageObject;
  ancestors: StorageObjectAncestor[];
  items: StorageObjectFolderItem[];
  total: number;
}

export interface StorageObjectCreate {
  name: string;
  isPublic: boolean;
  parent?: string;
  type: StorageObjectType;
  userId: string;
  file?: string;
  image?: string;
  video?: string;
}

export interface StorageObjectCreateWeb {
  name: string;
  isPublic: boolean;
  parent?: string;
  type: StorageObjectType;
  file?: string;
  image?: string;
  video?: string;
}

export interface StorageObjectUpdateSet {
  name?: string;
  isPublic?: boolean;
  parent?: string;
}

export interface StorageObjectUpdate {
  set?: StorageObjectUpdateSet;
}

export interface StorageObjectUpdateOne {
  query: StorageObjectQuery;
  update: StorageObjectUpdate;
}

export interface StorageObjectUpdateById {
  id: string;
  update: StorageObjectUpdate;
}

/**
 * Objects of one owner, deleted or moved together under one tree lock: all or none. With `userId`,
 * an object of another owner reads as missing.
 */
export interface StorageObjectDeleteMany {
  ids: string[];
  userId?: string;
}

/** A name taken in `parent` gets a ` (n)` suffix, as a move of one object does. */
export interface StorageObjectMoveMany {
  ids: string[];
  parent: string;
  userId?: string;
}

export interface StorageObjectMoveByIds {
  ids: string[];
  parent: string;
}

/**
 * Objects of one owner made public or private together under one tree lock: all or none. A folder
 * takes its whole subtree along. An object cannot be made private while its folder is public,
 * unless that folder is made private by the same call.
 */
export interface StorageObjectUpdatePublicMany {
  ids: string[];
  isPublic: boolean;
  userId?: string;
}

export interface StorageObjectUpdatePublicByIds {
  ids: string[];
  isPublic: boolean;
}

/**
 * A folder tree made under `parent` at once, under one tree lock: all or none. `paths` are
 * "/"-separated and relative to `parent` ("img", "img/2024"), each nested path's parent path listed
 * too. A top-level name taken in `parent` gets a ` (n)` suffix; the folders below it are new. Answered
 * in `paths` order.
 */
export interface StorageObjectCreateFolders {
  userId: string;
  parent: string;
  paths: string[];
}
