// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: storage/storage-object/storage-object.populates.proto

/* eslint-disable */
import type { File } from '../file/file';
import type { Image } from '../image/image';
import type { Video } from '../video/video';
import type { StorageObjectFolderStats, StorageObjectType } from './storage-object';

export interface StorageObjectPopulated {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: StorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  file?: File;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  image?: Image;
  video?: Video;
  folderStats?: StorageObjectFolderStats;
}

/**
 * An item of a folder listing: `StorageObjectPopulated` field for field (keep the two in step), plus
 * a preview. `previewUrl` is a signed, short-lived CDN URL — the image's small webp preview for a
 * READY image that has one, the Stream thumbnail for a READY video — and is absent for anything else,
 * an image still without a preview included: never the original. It is bound to no client address,
 * and nothing on the CDN resizes it.
 */
export interface StorageObjectFolderItem {
  id: string;
  createdAt: Date;
  updatedAt?: Date;
  name: string;
  isPublic: boolean;
  isFolder: boolean;
  type: StorageObjectType;
  userId: string;
  fileId?: string;
  parentId?: string;
  file?: File;
  folderPath?: string;
  imageId?: string;
  videoId?: string;
  image?: Image;
  video?: Video;
  folderStats?: StorageObjectFolderStats;
  previewUrl?: string;
}
